import assert from 'node:assert/strict';
import {GET,POST,PUT,DELETE} from '../app/api/v1/[...path]/route';
import {settings,one,run} from './platform';
import {signed} from '../server/security';
const base='https://framefinder.test';
async function call(path:string,method='GET',data?:unknown,cookie='',origin=base){const req=new Request(base+'/api/v1/'+path,{method,headers:{origin,cookie,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});return ({GET,POST,PUT,DELETE} as any)[method](req,{params:Promise.resolve({path:path.split('/')})}) as Promise<Response>;}
const signup=await call('auth/signup','POST',{name:'Test Viewer',username:'test_viewer',email:'viewer@example.com',password:'a lengthy test passphrase'});assert.equal(signup.status,200);const cookie=signup.headers.get('set-cookie')!.split(';')[0];const account=await(await call('auth/session','GET',undefined,cookie)).json() as any;assert.equal(account.user.username,'test_viewer');assert.equal(account.user.password,undefined);const row=await one<any>('SELECT * FROM accounts WHERE id=?',[account.user.id]);assert.notEqual(row.password,'a lengthy test passphrase');console.log('PASS signup, password hashing and session');
assert.equal((await call('movies')).status,401);assert.equal((await call('me','PUT',{name:'Bad',bio:'',languages:['English']},cookie,'https://evil.test')).status,403);assert.equal((await call('auth/signup','GET')).status,405);console.log('PASS authentication, CSRF and method restrictions');
assert.equal((await call('auth/login','POST',{identity:'test_viewer',password:'wrong'})).status,401);assert.equal((await call('auth/login','POST',{identity:'test_viewer',password:'a lengthy test passphrase'})).status,200);
assert.equal((await call('movies/1','PUT',{liked:true,watched:true,rating:9},cookie)).status,200);const film=await(await call('movies/1','GET',undefined,cookie)).json() as any;assert.equal(film.stats.likes,1);assert.equal(film.stats.watched,1);assert.equal(film.stats.rating,4.5);const recs=await(await call('recommendations','GET',undefined,cookie)).json() as any;assert.ok(!recs.movies.some((x:any)=>x.id===1));const cat=await(await call('movies','GET',undefined,cookie)).json() as any;assert.ok(cat.total>100);assert.equal(cat.movies.length,24);console.log('PASS persisted film state, real stats and catalog pagination');
const second=await call('auth/signup','POST',{name:'Other Viewer',username:'other_viewer',email:'other@example.com',password:'another test passphrase'});const cookie2=second.headers.get('set-cookie')!.split(';')[0];const state2=await(await call('state','GET',undefined,cookie2)).json() as any;assert.equal(state2.state.length,0);const asset='2d38b752-c94d-4d08-a91e-9f7e3d3eaac2';await run('INSERT INTO assets(id,user_id,kind,mime) VALUES(?,?,?,?)',[asset,account.user.id,'proof','image/png']);assert.equal((await call('assets/'+asset,'GET',undefined,cookie2)).status,404);console.log('PASS user isolation and private proof access');
const title='Interstellar';const pref={id:'test-alert',title,city:'Hyderabad',date:'2099-12-12',language:'English',edition:'Original release',formats:['2D'],theaterIds:['prasads'],timeFrom:'10:00',timeTo:'23:00',timeZone:'Asia/Kolkata',bookingUrl:'',kind:'booking-open'};
// Use the actual local directory id, never a guessed provider code.
const directory=await import('../data/theaters.json');pref.theaterIds=[directory.default[0].id];assert.equal((await call('alerts','POST',pref,cookie)).status,200);assert.equal((await call('alerts','POST',pref,cookie2)).status,404);assert.equal((await call('billing/order','POST',{},cookie)).status,503);console.log('PASS alert ownership and payments unavailable without configuration');
settings.BOOKING_WEBHOOK_SECRET='test-only-webhook-key';settings.BOOKING_FEED_READY='true';
async function event(id:string,override:Record<string,any>={}){const body=JSON.stringify({eventId:id,alertId:pref.id,title,city:pref.city,language:pref.language,edition:pref.edition,theaterId:pref.theaterIds[0],format:'2D',date:pref.date,time:'17:00',bookingUrl:'https://in.bookmyshow.com/movies/interstellar/ET00019066',observedAt:new Date().toISOString(),bookable:true,...override});const req=new Request(base+'/api/v1/webhooks/booking',{method:'POST',headers:{'x-booking-signature':signed(body,settings.BOOKING_WEBHOOK_SECRET)},body});return POST(req,{params:Promise.resolve({path:['webhooks','booking']})});}
assert.equal((await event('mismatch',{format:'IMAX 3D'})).status,400);for(const id of ['one','one','two','three','four'])assert.equal((await event(id)).status,200);assert.equal((await one<any>('SELECT COUNT(*) n FROM credit_uses'))!.n,3);assert.equal((await one<any>('SELECT COUNT(*) n FROM notifications'))!.n,3);console.log('PASS strict show matching, retry deduplication and three-credit limit');
await run('UPDATE accounts SET verified=1 WHERE id=?',[account.user.id]);settings.RAZORPAY_KEY_ID='rzp_test_example';settings.RAZORPAY_KEY_SECRET='test-secret';settings.BOOKING_FEED_READY='true';settings.ALERT_PACK_PRICE_PAISE='9900';settings.ALERT_PACK_CREDITS='10';settings.RAZORPAY_WEBHOOK_SECRET='test-webhook';const nativeFetch=globalThis.fetch;globalThis.fetch=async(input:any,init:any)=>{const url=String(input);if(url.endsWith('/orders'))return Response.json({id:'order_test',amount:9900,currency:'INR'});if(url.endsWith('/payments/pay_test'))return Response.json({id:'pay_test',order_id:'order_test',amount:9900,currency:'INR',status:'captured',amount_refunded:0});return nativeFetch(input,init);};
const orderResponse=await call('billing/order','POST',{amount:1,credits:9999},cookie);assert.equal(orderResponse.status,503);await run('INSERT INTO billing(order_id,user_id,amount,credits,created_at) VALUES(?,?,?,?,?)',['order_test',account.user.id,9900,10,new Date().toISOString()]);const payment={razorpay_order_id:'order_test',razorpay_payment_id:'pay_test',razorpay_signature:signed('order_test|pay_test','test-secret')};assert.equal((await call('billing/verify','POST',{...payment,razorpay_signature:'0'.repeat(64)},cookie)).status,400);assert.equal((await call('billing/verify','POST',payment,cookie2)).status,403);for(let i=0;i<2;i++)assert.equal((await call('billing/verify','POST',payment,cookie)).status,200);const billing=await(await call('billing','GET',undefined,cookie)).json() as any;assert.equal(billing.balance,10);console.log('PASS new payments disabled, existing payment signature rejection and idempotent captured-payment credits (mocked Razorpay)');
const ticket={movie:title,theater:'Test Theater',showAt:'2099-12-12T12:00:00Z',language:'English',format:'2D',quantity:2,faceValue:100000,price:90000,proofId:asset,reference:'TEST-BOOKING-123'};const listing=await call('tickets','POST',ticket,cookie);assert.equal(listing.status,200);const listingData=await listing.json() as any;assert.equal((await call('tickets','POST',ticket,cookie)).status,409);assert.equal((await call('tickets/'+listingData.id,'GET',undefined,cookie2)).status,404);assert.equal((await call('tickets','POST',{...ticket,reference:'different-ref',price:200000,publish:true},cookie)).status,200);console.log('PASS ticket submission, duplicate rejection, private pending listings and separate asking prices');

// A second account can discover opt-in public listings but cannot fetch their proof.
assert.equal((await(await call('tickets','GET',undefined,cookie2)).json() as any).tickets.length,0);
await run("INSERT INTO admin_reviews(id,ticket_id,admin_id,decision,note,created_at,proof_id) SELECT ?,id,?,'approved','Test approval',?,proof_id FROM tickets WHERE is_public=1",[crypto.randomUUID(),account.user.id,new Date().toISOString()]);await run('UPDATE tickets SET review_pending=0 WHERE is_public=1');
const publicTickets=await(await call('tickets','GET',undefined,cookie2)).json() as any;
assert.equal(publicTickets.tickets.length,1);const publicId=publicTickets.tickets[0].id;
const publicDetail=await(await call('tickets/'+publicId,'GET',undefined,cookie2)).json() as any;assert.equal(publicDetail.ticket.proof_id,undefined);assert.equal(publicDetail.ticket.reference_hash,undefined);
const convo=await(await call('conversations','POST',{ticketId:publicId},cookie2)).json() as any;assert.ok(convo.id);assert.equal((await call('conversations/'+convo.id,'GET',undefined,cookie)).status,200);
const third=await call('auth/signup','POST',{name:'Third Viewer',username:'third_viewer',email:'third@example.com',password:'a third test passphrase'});const cookie3=third.headers.get('set-cookie')!.split(';')[0];assert.equal((await call('conversations/'+convo.id,'GET',undefined,cookie3)).status,404);
const message={message:'Would you take ₹150?',nonce:crypto.randomUUID()};await call('conversations/'+convo.id+'/messages','POST',message,cookie2);await call('conversations/'+convo.id+'/messages','POST',message,cookie2);assert.equal((await one<any>('SELECT COUNT(*) n FROM chat_messages'))!.n,1);
const offer=await(await call('conversations/'+convo.id+'/offers','POST',{amount:15000},cookie2)).json() as any;assert.equal((await call('conversations/'+convo.id+'/offers/'+offer.id,'POST',{action:'accept'},cookie2)).status,403);assert.equal((await call('conversations/'+convo.id+'/offers/'+offer.id,'POST',{action:'accept'},cookie)).status,200);
assert.equal((await call('conversations/'+convo.id+'/offers/'+offer.id,'POST',{action:'accept'},cookie)).status,409);console.log('PASS second-account listing discovery, private chat isolation, message idempotency and offer permissions');
await run('UPDATE accounts SET verified=1 WHERE username=?',['other_viewer']);await run('UPDATE tickets SET status=? WHERE id=?',['verified',publicId]);settings.TICKET_PARTNER_URL='https://ticket-partner.test';settings.TICKET_PARTNER_TOKEN='test-token';let chargedAmount=0;const originalMock=globalThis.fetch;globalThis.fetch=async(input:any,init:any)=>{if(String(input)==='https://ticket-partner.test/checkout'){chargedAmount=JSON.parse(init.body).amount;return Response.json({url:'https://ticket-partner.test/pay'});}return originalMock(input,init)};
assert.equal((await call('tickets/'+publicId+'/checkout','POST',{},cookie2)).status,200);assert.equal(chargedAmount,15000);assert.equal((await call('tickets/'+publicId+'/checkout','POST',{},cookie2)).status,409);assert.equal((await call('conversations/'+convo.id+'/messages','POST',{message:'late message',nonce:crypto.randomUUID()},cookie2)).status,409);console.log('PASS negotiated checkout total, single reservation and closed-listing chat (mocked partner)');

const buyerTickets=await(await call('my-tickets','GET',undefined,cookie2)).json() as any;assert.equal(buyerTickets.tickets.length,1);assert.equal(buyerTickets.tickets[0].amount,15000);assert.equal(buyerTickets.tickets[0].status,'reserved');assert.ok(buyerTickets.tickets[0].reserved_at);assert.equal(buyerTickets.tickets[0].purchased_at,null);
assert.equal((await(await call('my-tickets','GET',undefined,cookie3)).json() as any).tickets.length,0);
assert.equal((await call('my-tickets')).status,401);
settings.TICKET_WEBHOOK_SECRET='receipt-test-secret';
const purchaseTime=new Date().toISOString();
async function ticketEvent(status:string){const raw=JSON.stringify({listingId:publicId,status,timestamp:Date.now(),purchasedAt:purchaseTime});const req=new Request(base+'/api/v1/webhooks/tickets',{method:'POST',headers:{'x-ticket-signature':signed(raw,settings.TICKET_WEBHOOK_SECRET)},body:raw});return POST(req,{params:Promise.resolve({path:['webhooks','tickets']})});}
assert.equal((await ticketEvent('completed')).status,200);
const confirmed=await(await call('my-tickets','GET',undefined,cookie2)).json() as any;assert.equal(confirmed.tickets[0].status,'completed');assert.equal(confirmed.tickets[0].purchased_at,purchaseTime);assert.ok(confirmed.tickets[0].confirmed_at);
await ticketEvent('completed');assert.equal((await one<any>('SELECT COUNT(*) n FROM ticket_receipts')).n,1);
await ticketEvent('refunded');assert.equal((await call('tickets/'+publicId,'GET',undefined,cookie2)).status,200);assert.equal((await call('tickets/'+publicId,'GET',undefined,cookie3)).status,404);
assert.equal((await(await call('my-tickets','GET',undefined,cookie2)).json() as any).tickets[0].status,'refunded');
console.log('PASS private ticket history, agreed checkout amount, partner purchase dates and idempotent status updates');

const seatAlert={id:crypto.randomUUID(),kind:'seat-release',city:'Hyderabad',theaterId:pref.theaterIds[0],title:'Interstellar',dates:['2099-12-12','2099-12-13'],bookingUrl:''};assert.equal((await call('seat-alerts','POST',seatAlert,cookie2)).status,200);assert.equal((await call('seat-alerts','POST',seatAlert,cookie)).status,404);assert.equal((await call('seat-alerts','POST',{...seatAlert,id:crypto.randomUUID(),dates:['2099-12-12','2099-12-12']},cookie2)).status,400);
settings.SEAT_FEED_READY='true';settings.SEAT_WEBHOOK_SECRET='seat-test-key';
const observed=Date.now()-10000;
async function seatEvent(seats:Record<string,string>,offset:number,extra:Record<string,unknown>={}){const data=JSON.stringify({alertId:seatAlert.id,provider:'fixture',sessionId:'show-one',layoutId:'layout-one',city:seatAlert.city,theaterId:seatAlert.theaterId,title:seatAlert.title,date:seatAlert.dates[0],time:'19:30',bookingUrl:'https://in.bookmyshow.com/movies/interstellar/ET00019066',observedAt:new Date(observed+offset).toISOString(),complete:true,seats,...extra});return POST(new Request(base+'/api/v1/webhooks/seats',{method:'POST',headers:{'x-seat-signature':signed(data,settings.SEAT_WEBHOOK_SECRET)},body:data}),{params:Promise.resolve({path:['webhooks','seats']})});}
assert.equal((await(await seatEvent({A1:'held',A2:'available'},0)).json() as any).baseline,true);assert.equal((await(await seatEvent({A1:'held',A2:'available'},1000)).json() as any).delivered,false);
const freed=await(await seatEvent({A1:'available',A2:'available'},2000)).json() as any;assert.deepEqual(freed.released,['A1']);assert.equal(freed.delivered,true);const seatNotice=await one<any>("SELECT message FROM notifications WHERE title LIKE '%seats released'");assert.ok(seatNotice.message.includes('A1'));assert.ok(seatNotice.message.includes('19:30'));assert.ok(seatNotice.message.includes('2099-12-12'));await seatEvent({A1:'available',A2:'available'},2000);const seatUses=await one<any>('SELECT COUNT(*) n FROM credit_uses WHERE user_id=(SELECT id FROM accounts WHERE username=?)',['other_viewer']);assert.equal(seatUses.n,1);assert.equal((await seatEvent({A1:'available'},3000,{complete:false})).status,400);assert.equal((await seatEvent({A1:'available'},3000,{date:'2099-12-14'})).status,400);assert.equal((await(await seatEvent({A1:'held'},0)).json() as any).delivered,false);console.log('PASS multi-date seat alerts, baseline, true seat transitions, duplicate events and invalid snapshots');
await call('auth/logout','POST',{},cookie);assert.equal((await call('state','GET',undefined,cookie)).status,401);console.log('PASS logout revokes session');

const {seatAlertSchema}=await import('../lib/seat-alerts');
const dateSeries=Array.from({length:31},(_,i)=>new Date(Date.UTC(2030,0,1+i)).toISOString().slice(0,10));
const datePref={id:crypto.randomUUID(),kind:'seat-release',city:'Hyderabad',theaterId:'',title:'Test film',dates:dateSeries,bookingUrl:''};
const {theaters:dateTheaters}=await import('../lib/booking');datePref.theaterId=dateTheaters[0].id;
assert.equal(seatAlertSchema.safeParse(datePref).success,true);
assert.equal(seatAlertSchema.safeParse({...datePref,dates:[...dateSeries,'2030-02-01']}).success,false);
console.log('PASS 31 seat-alert dates accepted and oversized selections rejected');
