import assert from 'node:assert/strict';
import {GET,POST,PUT,DELETE} from '../app/api/v1/[...path]/route';
import {run,one,all,settings,putAsset,getAsset} from './platform';
const base='https://framefinder.test';
async function call(path:string,method='GET',data?:unknown,cookie=''){return await ({GET,POST,PUT,DELETE} as any)[method](new Request(base+'/api/v1/'+path,{method,headers:{origin:base,cookie,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})}),{params:Promise.resolve({path:path.split('?')[0].split('/')})}) as Response;}
const password='member experience password';
async function account(username:string){const r=await call('auth/signup','POST',{name:username,username,email:username+'@example.com',password});assert.equal(r.status,200);return {cookie:r.headers.getSetCookie()[0].split(';')[0],username,...await one<any>('SELECT id FROM accounts WHERE username=?',[username])};}
const owner=await account('experience_owner'),member=await account('experience_member'),peer=await account('experience_peer');settings.ADMIN_USER_IDS=owner.id;
const prefs={active:true,ticketUpdates:true,communityUpdates:false,selectedPlan:'plus',billingPeriod:'yearly'};
assert.equal((await call('subscriptions','POST',prefs,member.cookie)).status,200);let r=await(await call('subscriptions','GET',undefined,member.cookie)).json();assert.equal(r.preferences.selected_plan,'plus');assert.equal(r.preferences.billing_period,'yearly');assert.equal(r.plan.paymentsEnabled,false);
assert.equal((await call('subscriptions','POST',{...prefs,selectedPlan:'made-up'},member.cookie)).status,400);
assert.equal((await(await call('notifications/setup','GET',undefined,member.cookie)).json()).prompted,false);await call('notifications/setup','POST',{},member.cookie);assert.equal((await(await call('notifications/setup','GET',undefined,member.cookie)).json()).prompted,true);
const rating={id:crypto.randomUUID(),kind:'rating',category:'feedback',rating:4,message:'My private rating',publicConsent:false};await call('feedback','POST',rating,member.cookie);r=await(await call('community-reviews','GET',undefined,member.cookie)).json();assert.equal(r.own[0].message,'My private rating');assert.equal(r.own[0].consent,0);assert.equal(r.reviews.length,0);assert.equal((await call('community-reviews/'+rating.id,'POST',{},peer.cookie)).status,404);assert.equal((await call('community-reviews/'+rating.id,'POST',{},member.cookie)).status,200);assert.equal((await(await call('community-reviews','GET',undefined,peer.cookie)).json()).reviews.length,0);
const conversation=crypto.randomUUID();await run('INSERT INTO conversations(id,ticket_id,buyer_id,seller_id,created_at,updated_at) VALUES(?,?,?,?,?,?)',[conversation,'test-ticket',member.id,peer.id,'2026-09-11','2026-09-11']);await run('UPDATE accounts SET avatar=? WHERE id=?',['/profile-pictures/m6.jpg',peer.id]);await run('INSERT INTO notifications(id,user_id,title,message,link,created_at) VALUES(?,?,?,?,?,?)',['request:test',member.id,'Discuss a movie','Let’s discuss','/messages/'+conversation,'2026-09-11']);await run('INSERT INTO notifications(id,user_id,title,message,link,created_at) VALUES(?,?,?,?,?,?)',['admin:test',member.id,'Team update','Welcome','/notifications','2026-09-11']);r=await(await call('notifications','GET',undefined,member.cookie)).json();assert.equal(r.notifications.find((n:any)=>n.id==='request:test').sender_avatar,'/profile-pictures/m6.jpg');assert.equal(r.notifications.find((n:any)=>n.id==='admin:test').sender_avatar,'/profile-pictures/admin-notification.png');
await call('movies/2','PUT',{rating:8,watched:true},member.cookie);
const change={action:'deactivate',confirmUsername:member.username,password};assert.equal((await call('account','POST',{...change,confirmUsername:'wrong'},member.cookie)).status,400);assert.equal((await call('account','POST',{...change,password:'wrong'},member.cookie)).status,401);assert.equal((await call('account','POST',change,member.cookie)).status,200);assert.equal((await call('state','GET',undefined,member.cookie)).status,401);assert.equal((await call('admin/members','POST',{action:'restore',userId:member.id,confirmUsername:member.username},owner.cookie)).status,403);
const login=await call('auth/login','POST',{identity:member.username,password});assert.equal(login.status,200);member.cookie=login.headers.getSetCookie()[0].split(';')[0];assert.equal((await(await call('state','GET',undefined,member.cookie)).json()).state[0].rating,8);
const asset=crypto.randomUUID();await putAsset(asset,new ArrayBuffer(4),'image/png');await run('INSERT INTO assets(id,user_id,kind,mime) VALUES(?,?,?,?)',[asset,member.id,'avatar','image/png']);await run('INSERT INTO chat_messages(id,conversation_id,sender_id,message,created_at) VALUES(?,?,?,?,?)',[crypto.randomUUID(),conversation,member.id,'Private message','2026-09-11']);
assert.equal((await call('account','POST',{...change,action:'delete'},member.cookie)).status,200);assert.equal((await call('state','GET',undefined,member.cookie)).status,401);assert.equal((await call('auth/login','POST',{identity:member.username,password})).status,401);assert.equal((await one<any>('SELECT name FROM accounts WHERE id=?',[member.id])).name,'Deleted member');assert.equal((await all('SELECT * FROM social_state WHERE user_id=?',[member.id])).length,0);assert.equal((await all('SELECT * FROM chat_messages WHERE sender_id=?',[member.id])).length,0);assert.equal((await all('SELECT * FROM member_feedback WHERE user_id=?',[member.id])).length,0);assert.equal(await getAsset(asset),null);
const blocked=await account('experience_blocked');await run('INSERT INTO tickets(id,seller_id,movie,theater,show_at,language,format,quantity,face_value,price,proof_id,reference_hash,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[crypto.randomUUID(),blocked.id,'Film','Cinema','2099-01-01','Telugu','2D',1,100,100,crypto.randomUUID(),crypto.randomUUID(),'reserved','2026-09-11']);assert.equal((await call('account','POST',{action:'delete',confirmUsername:blocked.username,password},blocked.cookie)).status,409);assert.equal((await call('state','GET',undefined,blocked.cookie)).status,200);
console.log('PASS saved plan previews, one-time notification choice, private rating visibility, sender pictures, credential checks, deactivation/reactivation, irreversible profile erasure and active-exchange guard');

const googleOnly=await account('experience_google');await run('UPDATE accounts SET password=NULL,google_id=? WHERE id=?',['google-test-sub',googleOnly.id]);
assert.equal((await call('account','POST',{action:'delete',confirmUsername:googleOnly.username,code:'123456'},googleOnly.cookie)).status,401);
const {hash}=await import('../server/security');await run('INSERT INTO auth_tokens(token,user_id,purpose,expires) VALUES(?,?,?,?)',[hash(googleOnly.id+':account:123456'),googleOnly.id,'account-action','2000-01-01']);
assert.equal((await call('account','POST',{action:'delete',confirmUsername:googleOnly.username,code:'123456'},googleOnly.cookie)).status,401);
settings.RESEND_API_KEY='test-resend';settings.MAIL_FROM='test@example.com';let sentCode='';const originalFetch=globalThis.fetch;
globalThis.fetch=(async(input:any,init:any)=>{assert.equal(String(input),'https://api.resend.com/emails');const mail=JSON.parse(init.body);assert.equal(mail.to[0],'experience_google@example.com');sentCode=mail.text.match(/code is (\d{6})/)[1];return Response.json({id:'test-mail'});}) as any;
assert.equal((await call('account/confirmation-code','POST',{},googleOnly.cookie)).status,200);globalThis.fetch=originalFetch;
assert.equal((await call('account','POST',{action:'delete',confirmUsername:googleOnly.username,code:sentCode},googleOnly.cookie)).status,200);
assert.equal((await all('SELECT * FROM auth_tokens WHERE user_id=?',[googleOnly.id])).length,0);
console.log('PASS email-only account deletion rejects missing/expired codes and consumes the confirmed one-time code (mail mocked)');

const {catalog,audienceScore,movies}=await import('../server/catalog');assert.equal(catalog.length,811);const additions=catalog.filter(m=>m.id>=1000000);assert.equal(additions.length,500);assert.ok(additions.every(m=>(m.audienceRating||0)>=7&&(m.audienceVotes||0)>=100&&m.poster.startsWith('https://image.tmdb.org/')));assert.equal(new Set(catalog.map(m=>m.id)).size,catalog.length);
const discovery=await movies(new URL(base+'/?language=Telugu'));assert.ok(discovery.movies.every(m=>m.language==='Telugu'));for(let i=1;i<discovery.movies.length;i++)assert.ok(audienceScore(discovery.movies[i-1])>=audienceScore(discovery.movies[i]));
console.log('PASS 500 additional unique audience-rated films and confidence-weighted Telugu discovery');
