import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GET,POST,PUT} from '../app/api/v1/[...path]/route';
import {one,run,settings} from './platform';
import {pictureCollections,picturePath,visiblePicture} from '../lib/profile-pictures';
const base='https://framefinder.test';
async function call(path:string,method='GET',data?:unknown,cookie=''){return ({GET,POST,PUT} as any)[method](new Request(base+'/api/v1/'+path,{method,headers:{origin:base,cookie,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})}),{params:Promise.resolve({path:path.split('?')[0].split('/')})}) as Promise<Response>;}
async function account(username:string,name:string,picture=''){const r=await call('auth/signup','POST',{name,username,email:username+'@example.com',password:'test account password',profilePicture:picture});assert.equal(r.status,200);return {cookie:r.headers.getSetCookie()[0].split(';')[0],...(await one<any>('SELECT id FROM accounts WHERE username=?',[username]))};}
for(const files of Object.values(pictureCollections))for(const file of files)assert.ok(fs.existsSync('public'+picturePath(file)));
assert.equal(visiblePicture('/api/v1/avatar?design=legacy'),'');
const owner=await account('controls_owner','Owner Name'),member=await account('controls_member','Member Full Name','/profile-pictures/f5.jpg'),stranger=await account('controls_stranger','Another Name');settings.ADMIN_USER_IDS=owner.id;
const session=await(await call('auth/session','GET',undefined,member.cookie)).json();assert.equal(session.user.name,'Member Full Name');assert.equal(session.user.avatar,'/profile-pictures/f5.jpg');
const exact=await(await call('members?q=controls_member','GET',undefined,owner.cookie)).json();assert.equal(exact.members[0].id,member.id);
const results=await(await call('members?q=full%20name','GET',undefined,owner.cookie)).json();assert.equal(results.members[0].id,member.id);assert.equal(results.members[0].name,'Member Full Name');assert.equal(results.members[0].avatar,'/profile-pictures/f5.jpg');assert.equal(results.members[0].email,undefined);
assert.equal((await call('me/picture','POST',{picture:'https://evil.test/avatar.png'},member.cookie)).status,400);
assert.equal((await call('me/picture','POST',{picture:'/profile-pictures/missing.jpg'},member.cookie)).status,400);
assert.equal((await call('me/picture','POST',{picture:'/profile-pictures/m3.webp',userId:owner.id},member.cookie)).status,400);
assert.equal((await call('me/picture','POST',{picture:'/profile-pictures/m3.webp'},member.cookie)).status,200);
assert.equal((await(await call('auth/session','GET',undefined,member.cookie)).json()).user.avatar,'/profile-pictures/m3.webp');
assert.equal((await call('me/picture','POST',{picture:''},member.cookie)).status,200);assert.equal((await(await call('auth/session','GET',undefined,member.cookie)).json()).user.avatar,'');
console.log('PASS all 13 picture assets, persistent selected pictures, neutral fallback, display-name search and picture validation');
assert.equal((await call('admin/members','GET',undefined,member.cookie)).status,403);
const payload={userId:member.id,confirmUsername:'controls_member',action:'remove'};
assert.equal((await call('admin/members','POST',payload,stranger.cookie)).status,403);
assert.equal((await call('admin/members','POST',{...payload,confirmUsername:'wrong'},owner.cookie)).status,400);
assert.equal((await call('admin/members','POST',{...payload,userId:owner.id,confirmUsername:'controls_owner'},owner.cookie)).status,403);
const ticket=crypto.randomUUID();await run('INSERT INTO tickets(id,seller_id,movie,theater,show_at,language,format,quantity,face_value,price,proof_id,reference_hash,created_at,is_public,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1,?)',[ticket,member.id,'Test Movie','Test Theater','2099-01-01T12:00:00Z','Telugu','2D',1,20000,18000,crypto.randomUUID(),'controls-ticket',new Date().toISOString(),'verified']);
assert.equal((await call('admin/members','POST',payload,owner.cookie)).status,409);assert.equal(await one('SELECT user_id FROM removed_accounts WHERE user_id=?',[member.id]),null);
await run("UPDATE tickets SET status='pending_verification' WHERE id=?",[ticket]);
await call('members/controls_member/follow','POST',{following:true},stranger.cookie);await call('movies/2','PUT',{watched:true,review:'An earlier review.'},member.cookie);
const conversation=await(await call('conversations','POST',{ticketId:ticket},stranger.cookie)).json();
assert.equal((await call('admin/members','POST',payload,owner.cookie)).status,200);
assert.equal((await call('members/controls_member','GET',undefined,stranger.cookie)).status,404);
assert.equal((await(await call('members?q=controls_member','GET',undefined,stranger.cookie)).json()).members.length,0);
assert.equal((await(await call('feed','GET',undefined,stranger.cookie)).json()).activity.length,0);
assert.equal((await call('movies/2','PUT',{watched:false},member.cookie)).status,401);
assert.equal((await call('auth/login','POST',{identity:'controls_member',password:'test account password'})).status,403);
assert.equal((await one<any>('SELECT is_public FROM tickets WHERE id=?',[ticket])).is_public,0);
assert.equal((await call('conversations/'+conversation.id+'/messages','POST',{message:'Hello',nonce:crypto.randomUUID()},stranger.cookie)).status,409);
assert.ok(await one('SELECT id FROM accounts WHERE id=?',[member.id]));assert.ok(await one('SELECT key FROM social_state WHERE user_id=?',[member.id]));
const adminResults=await(await call('admin/members?q=controls_member','GET',undefined,owner.cookie)).json();assert.ok(adminResults.members[0].removed_at);
assert.equal((await call('admin/members','POST',{...payload,action:'restore'},owner.cookie)).status,200);
assert.equal((await call('members/controls_member','GET',undefined,stranger.cookie)).status,200);
assert.equal((await call('auth/login','POST',{identity:'controls_member',password:'test account password'})).status,200);
assert.equal((await one<any>('SELECT is_public FROM tickets WHERE id=?',[ticket])).is_public,0);
console.log('PASS admin-only member removal, exact identity confirmation, protected admins, active-exchange guard, revoked sessions, hidden profiles and restoration');
