'use client';
import {useState} from 'react';
import {api,useLoad,clearClientData} from './client-data';
import {announceSignOut} from './session-provider';
export default function AccountLifecycle({username}:{username:string}){
 const[action,setAction]=useState(''),[confirmation,setConfirmation]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const{data,error}=useLoad('account');
 async function confirm(){setBusy(true);setMessage('');try{const result=await api('account',{action,confirmUsername:confirmation,...(data.hasPassword?{password}:{code})});clearClientData();announceSignOut();location.assign(result.next);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel account-lifecycle"><h2>Your account, your choice.</h2><p>Take a break, or permanently delete your account.</p><div className="actions"><button type="button" className="button secondary" onClick={()=>{setAction('deactivate');setMessage('');}}>Temporarily deactivate</button><button type="button" className="text-button" onClick={()=>{setAction('delete');setMessage('');}}>Permanently delete my account</button></div>{action&&<div className="account-lifecycle-confirm"><h3>{action==='delete'?'Permanently delete your account?':'Take a break from FrameFinder?'}</h3><p>{action==='delete'?'Your profile, ratings, reviews, saved alerts and messages will be erased. Uploaded files are queued for secure removal. Anonymized transaction records remain. You cannot undo this.':'Your profile and listings will be hidden and all devices signed out. Signing in again restores your profile and diary. Listings stay hidden until you publish them again.'}</p><p className="small">Complete any active ticket exchanges first.</p><label>Type {username} to confirm<input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{data?.hasPassword?<label>Current password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>:data&&<><button type="button" className="button secondary" disabled={busy||!data.emailConfirmationAvailable} onClick={async()=>{setBusy(true);try{await api('account/confirmation-code',{});setMessage('Check your account email for a confirmation code.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Send confirmation code</button>{!data.emailConfirmationAvailable&&<p>Email confirmation is currently unavailable. Try again once email delivery is restored.</p>}<label>Email confirmation code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label></>}<div className="actions"><button type="button" className="button primary" disabled={busy||!data||confirmation!==username||!(data.hasPassword?password:code.length===6)} onClick={confirm}>{busy?'Please wait…':action==='delete'?'Delete permanently':'Deactivate account'}</button><button type="button" className="text-button" disabled={busy} onClick={()=>{setAction('');setPassword('');setCode('');}}>Keep my account</button></div></div>}{(error||message)&&<p role="status">{error||message}</p>}</section>;
}
