'use client';
import {useState,type FormEvent} from 'react';
import {api,useLoad,clearClientData} from './client-data';
import {announceSignOut} from './session-provider';
export default function AccountLifecycle({username}:{username:string}){
 const[action,setAction]=useState(''),[confirmation,setConfirmation]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const{data,error}=useLoad('account');
 function choose(next:string){setAction(next);setConfirmation('');setPassword('');setCode('');setMessage('');}
 async function confirm(e:FormEvent){e.preventDefault();setMessage('');const name=confirmation.trim().replace(/^@/,'');if(name!==username){setMessage('Type '+username+' exactly to confirm your account.');return;}if(action==='delete'){if(!data){setMessage('Your account confirmation options are still loading. Please try again.');return;}if(data.hasPassword&&!password){setMessage('Enter your current password to permanently delete your account.');return;}if(!data.hasPassword&&!/^\d{6}$/.test(code)){setMessage('Enter the six-digit code sent to your account email.');return;}}
  setBusy(true);try{const result=await api('account',{action,confirmUsername:name,...(action==='delete'?(data.hasPassword?{password}:{code}):{})});clearClientData();announceSignOut();location.assign(result.next);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel account-lifecycle"><h2>Your account, your choice.</h2><p>Take a break, or permanently delete your account.</p><div className="actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>choose('deactivate')}>Temporarily deactivate</button><button type="button" className="text-button" disabled={busy} onClick={()=>choose('delete')}>Permanently delete my account</button></div>{action&&<form className="account-lifecycle-confirm" onSubmit={confirm}><h3>{action==='delete'?'Permanently delete your account?':'Temporarily deactivate your account?'}</h3><p>{action==='delete'?'Your profile, ratings, reviews, saved alerts and messages will be erased. Uploaded files are queued for secure removal. Anonymized transaction records remain. You cannot undo this.':'Your profile and listings will be hidden and all devices signed out. Signing in again restores your profile and diary. Listings stay hidden until you publish them again.'}</p><p className="small">Complete any active ticket exchanges first.</p><label>Type your username: <strong>{username}</strong><input autoFocus autoComplete="off" autoCapitalize="none" spellCheck={false} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{action==='delete'&&(data?.hasPassword?<label>Current password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>:data?<><button type="button" className="button secondary" disabled={busy||!data.emailConfirmationAvailable} onClick={async()=>{setBusy(true);try{await api('account/confirmation-code',{});setMessage('Check your account email for a confirmation code.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Send confirmation code</button>{!data.emailConfirmationAvailable&&<p>Email confirmation is currently unavailable. Permanent deletion needs email verification; temporary deactivation remains available.</p>}<label>Email confirmation code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label></>:<p role="status">{error||'Loading confirmation options…'}</p>)}{message&&<p className="notice" role="alert">{message}</p>}<div className="account-confirm-actions"><button type="submit" className="button primary" disabled={busy}>{busy?'Please wait…':action==='delete'?'Confirm permanent deletion':'Confirm temporary deactivation'}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>choose('')}>Keep my account</button></div></form>}</section>;
}
