'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {api,useDebounced,useLoad} from './client-data';
import ProfilePhoto from './profile-photo';
export default function AdminNotifications({recipientId=''}:{recipientId?:string}){
 const[q,setQ]=useState(''),[selected,setSelected]=useState<any[]>([]),[audience,setAudience]=useState('selected'),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const id=useRef('');const query=useDebounced(q);const{data,error}=useLoad('admin/recipients?q='+encodeURIComponent(query));
 useEffect(()=>{if(!recipientId)return;let current=true;api('admin/recipients?id='+encodeURIComponent(recipientId)).then(d=>{if(current)setSelected(d.members);}).catch(e=>current&&setStatus(e.message));return()=>{current=false};},[recipientId]);
 useEffect(()=>{id.current=crypto.randomUUID();setPreview(false);},[audience,title,message,selected]);
 async function submit(e:FormEvent){e.preventDefault();setStatus('');if(!preview){setPreview(true);return;}setBusy(true);try{const r=await api('admin/notify',{id:id.current,audience,...(audience==='selected'?{userIds:selected.map(m=>m.id)}:{}),title,message});setStatus('Notification sent to '+r.sent+' member'+(r.sent===1?'':'s')+'.');setMessage('');setTitle('');setPreview(false);}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 return <form className="panel admin-notification-form" onSubmit={submit}><h2>Send a notification</h2><p className="muted">Messages appear in members’ Notifications.</p>{(status||error)&&<p className="notice" role="status">{status||error}</p>}<fieldset disabled={busy}><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="selected">Choose members</option><option value="all">All active members ({data?.total??'…'})</option><option value="subscribers">Subscribers who enabled community updates</option></select></label>{audience==='selected'&&<><label>Search members<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name or username"/></label><div className="recipient-picks">{selected.map(m=><button type="button" className="tag" key={m.id} onClick={()=>setSelected(selected.filter(x=>x.id!==m.id))} aria-label={'Remove '+m.name}>{m.name} ×</button>)}</div><div className="recipient-results">{data?.members.filter((m:any)=>!selected.some(x=>x.id===m.id)).map((m:any)=><button type="button" key={m.id} disabled={selected.length>=50} onClick={()=>setSelected([...selected,m])}><ProfilePhoto name={m.name} src={m.avatar}/><span><strong>{m.name}</strong><small>@{m.username}</small></span><span>Add</span></button>)}{data&&!data.members.length&&<p>No matching members.</p>}</div></>}<label>Title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} required/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} rows={5} required/></label>{preview&&<div className="notice"><strong>Ready to send {audience==='all'?'to all '+(data?.total??'active')+' members':audience==='subscribers'?'to subscribed members':'to '+selected.length+' selected members'}?</strong><p>{title}</p><p className="support-message">{message}</p></div>}<div className="actions">{preview&&<button type="button" className="button secondary" onClick={()=>setPreview(false)}>Edit</button>}<button className="button primary" disabled={busy||(audience==='selected'&&!selected.length)}>{busy?'Sending…':preview?'Send notification':'Review notification'}</button></div></fieldset></form>;
}
