'use client';
import {useState,useRef,useEffect} from 'react';
import {api,useLoad,useDebounced} from './client-data';
import ProfilePhoto from './profile-photo';
export default function AdminMembers(){const[q,setQ]=useState(''),[revision,refresh]=useState(0),[selected,setSelected]=useState<any>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const query=useDebounced(q),{data,error}=useLoad('admin/members?q='+encodeURIComponent(query),revision),dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{if(selected&&!dialog.current?.open)dialog.current?.showModal();if(!selected&&dialog.current?.open)dialog.current?.close();},[selected]);
 async function apply(){setBusy(true);setMessage('');try{await api('admin/members',{userId:selected.id,action:selected.removed_at?'restore':'remove',confirmUsername:confirmation});setMessage(selected.removed_at?'Member restored. They can sign in again.':'Member removed. Sign-in is disabled and their profile is hidden.');setSelected(null);refresh(n=>n+1);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel admin-members"><h2>Manage members</h2><label>Find an account<input placeholder="Name, username or email" value={q} onChange={e=>setQ(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}{message&&!selected&&<p className="notice" role="status">{message}</p>}<div className="admin-member-list">{data?.members.map((member:any)=><div className="admin-member-row" key={member.id}><ProfilePhoto name={member.name} src={member.avatar}/><div><strong>{member.name}</strong><small>@{member.username} · {member.email}</small>{member.removed_at&&<span className="tag">Removed</span>}</div><button type="button" className="button secondary" disabled={member.protected||busy} onClick={e=>{trigger.current=e.currentTarget;setSelected(member);setConfirmation('');setMessage('');}}>{member.protected?'Protected':member.removed_at?'Restore':'Remove member'}</button></div>)}{data&&!data.members.length&&<p>No matching accounts.</p>}</div><dialog ref={dialog} className="member-confirm-dialog" onCancel={e=>{if(busy)e.preventDefault();else setSelected(null);}} onClose={()=>{setSelected(null);trigger.current?.focus();}}>{selected&&<><h2>{selected.removed_at?'Restore':'Remove'} {selected.name}?</h2><p>{selected.removed_at?'This restores sign-in and profile visibility. Hidden ticket listings stay private.':'This disables sign-in, signs them out and hides their profile and listings. Records are retained so the action can be reversed.'}</p><label>Type @{selected.username} to confirm<input autoFocus autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={selected.username}/></label>{message&&<p className="notice error" role="alert">{message}</p>}<div className="actions"><button className="button secondary" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button><button className="button primary" disabled={busy||confirmation!==selected.username} onClick={apply}>{busy?'Saving…':selected.removed_at?'Restore member':'Remove member'}</button></div></>}</dialog></section>;
}
