'use client';
import {useState,type FormEvent} from 'react';
import {Ticket,Users,Bell,MessageSquare,Star,ArrowLeft} from 'lucide-react';
import AdminMembers from './admin-members';
import AdminNotifications from './admin-notifications';
import Link from './app-link';
import {api,useLoad} from './client-data';
import {MovieArtwork} from './movie-picker';
const sections=[{id:'reviews',title:'Ticket reviews',description:'Approve proofs and request corrections',Icon:Ticket},{id:'members',title:'Manage members',description:'Find accounts and send a notification',Icon:Users},{id:'notifications',title:'Send notifications',description:'One member, selected members or everyone',Icon:Bell},{id:'support',title:'Feedback & support',description:'Resolve requests and feature public ratings',Icon:MessageSquare},{id:'subscriptions',title:'Subscriptions',description:'View memberships and saved plan choices',Icon:Star}];
function SubscriptionMembers(){const{data,error}=useLoad('admin/subscriptions');return <div className="panel"><h2>Subscriptions</h2>{error&&<p role="alert">{error}</p>}<p>{data?.total??0} active free memberships · Paid plan choices are previews</p><div className="admin-member-list">{data?.members.map((m:any)=><div className="admin-member-row" key={m.id}><div><strong>{m.name}</strong><small>@{m.username} · {m.active?'Active':'Cancelled'}</small><small>Plan choice: {m.selected_plan} · {m.billing_period}</small><small>Ticket updates {m.ticket_updates?'on':'off'} · Community updates {m.community_updates?'on':'off'}</small></div><Link className="button secondary" href={'/admin/notifications/'+m.id}>Notify</Link></div>)}</div>{data&&!data.members.length&&<p>No subscriptions yet.</p>}<p className="small">Showing the 100 most recently updated subscriptions.</p></div>;}
export default function AdminPanel({section='',recipientId=''}:{section?:string;recipientId?:string}){const[revision,refresh]=useState(0),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const{data,error}=useLoad('admin',revision);const current=sections.find(s=>s.id===section);
 async function submit(e:FormEvent<HTMLFormElement>,path:string){e.preventDefault();const form=e.currentTarget;setBusy(true);setStatus('');try{await api('admin/'+path,Object.fromEntries(new FormData(form)));setStatus(path==='review'?'Review saved and seller notified.':'Support status updated.');refresh(n=>n+1);}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 return <section className="section admin-workspace"><p className="eyebrow">ADMINISTRATION</p><div className="section-heading"><h1>{current?.title||'Your admin workspace.'}</h1>{current&&<Link className="button secondary" href="/admin"><ArrowLeft size={17}/>All sections</Link>}</div>{!current?<div className="admin-section-grid">{sections.map(({id,title,description,Icon})=><Link className="panel admin-section-card" href={'/admin/'+id} key={id}><Icon size={30}/><h2>{title}</h2><p>{description}</p>{id==='reviews'&&<strong>{data?.tickets.length??'…'} waiting</strong>}{id==='support'&&<strong>{data?.feedback.filter((f:any)=>f.status==='open').length??'…'} open</strong>}</Link>)}</div>:<nav className="admin-section-tabs" aria-label="Administration">{sections.map(s=><Link key={s.id} href={'/admin/'+s.id} aria-current={s.id===section?'page':undefined}>{s.title}</Link>)}</nav>}{(error||status)&&<p className="notice" role="status">{error||status}</p>}
 {section==='members'&&<AdminMembers/>}{section==='notifications'&&<AdminNotifications key={recipientId} recipientId={recipientId}/>} {section==='subscriptions'&&<SubscriptionMembers/>}
 {section==='reviews'&&data&&<><p className="muted">Check the private proof before approving a listing. Only approved, published listings appear in Ticket Exchange.</p>{!data.tickets.length&&<p className="notice">All caught up. No tickets need review.</p>}<div className="ticket-grid">{data.tickets.map((t:any)=><form key={t.id} className="panel" onSubmit={e=>submit(e,'review')}><div className="alert-movie-heading"><MovieArtwork title={t.movie}/><h3>{t.movie}</h3></div><p>@{t.username} · {t.theater}</p><p>{new Date(t.show_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p><p>Face value ₹{t.face_value/100} · Asking ₹{t.price/100}</p><a target="_blank" rel="noreferrer" href={'/api/v1/admin/proof/'+t.id}>Open private booking proof</a><input type="hidden" name="ticketId" value={t.id}/><input type="hidden" name="proofId" value={t.proof_id}/>{!t.can_review&&<p className="notice">Another administrator must review your own ticket.</p>}<fieldset disabled={busy||!t.can_review}><label>Decision<select name="decision" required><option value="needs_info">Request corrected proof</option><option value="approved">Approve listing</option><option value="rejected">Reject listing</option></select></label><label>Reason or instructions<textarea name="note" minLength={5} maxLength={1000} required/></label><button className="button primary">Save review & notify seller</button></fieldset></form>)}</div></>}
 {section==='support'&&data&&<div className="support-inbox">{data.feedback.length?data.feedback.map((f:any)=><article className="panel" key={f.id}><p className="eyebrow">{f.kind} · {f.category} · {f.status}</p><h3>@{f.username}{f.rating?` · ${f.rating}/5 ★`:null}</h3><p className="support-message">{f.message||'Rating without a comment.'}</p><p className="small">{new Date(f.created_at).toLocaleString('en-IN')}</p><form onSubmit={e=>submit(e,'feedback')}><input type="hidden" name="id" value={f.id}/><input type="hidden" name="status" value={f.status==='open'?'resolved':'open'}/><button className="button secondary" disabled={busy}>{f.status==='open'?'Mark resolved':'Reopen'}</button></form>{f.kind==='rating'&&f.rating>=4&&!!f.consent&&<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('admin/publish-feedback',{id:f.id,publish:!f.published});refresh(n=>n+1);setStatus(f.published?'Rating removed from subscription page.':'Rating featured on subscription page.');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}}>{f.published?'Unpublish rating':'Feature on subscription page'}</button>}{!f.consent&&<p className="small">Private feedback</p>}</article>):<p>No feedback or support requests yet.</p>}</div>}
 </section>;
}
