'use client';
import {useState} from 'react';
import Link from './app-link';
import {api,useLoad} from './client-data';
export default function AlertPlans(){
 const[revision,refresh]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const{data,error}=useLoad('billing',revision);
 async function buy(){setBusy(true);setMessage('');try{const order=await api('billing/order',{});if(!(window as any).Razorpay)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Checkout could not load. Please retry.'));document.head.appendChild(script);});const checkout=new (window as any).Razorpay({key:order.key,amount:order.amount,currency:order.currency,order_id:order.orderId,name:order.name,description:order.description,theme:{color:'#3b671f'},handler:async(result:any)=>{try{await api('billing/verify',result);refresh(n=>n+1);setMessage('Payment verified. Your alert credits are ready.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}},modal:{ondismiss:()=>setBusy(false)}});checkout.on('payment.failed',()=>{setMessage('Payment was not completed. No credits have been added.');setBusy(false);});checkout.open();}catch(e){setMessage((e as Error).message);setBusy(false);}}
 return <section className="section help-page"><p className="eyebrow">BOOKING ALERTS</p><h1>Alert plans & credits.</h1><p className="lede">Choose your shows. Get notified when matching bookings open.</p>{(error||message)&&<p className="notice" role="status">{error||message}</p>}<div className="panel credit-balance"><div><span>Available credits</span><h2>{data?data.balance:'…'}</h2></div><Link className="button secondary" href="/booking-alerts">Manage alerts</Link></div><div className="plans-grid"><article className="panel plan-card"><p className="eyebrow">STARTER</p><h2>Try booking alerts</h2><p className="plan-price">Free</p><ul><li>3 starter alert credits per account</li><li>Choose movies, theaters and show times</li><li>Read matching alerts in Notifications</li></ul><Link className="button secondary" href="/booking-alerts">Choose your shows</Link></article><article className="panel plan-card"><p className="eyebrow">ALERT PASS</p><h2>{data?.credits||10} alert credits</h2><p className="plan-price">{data?.price?'₹'+(data.price/100).toFixed(0):'Pricing coming soon'}</p><p>One-time purchase · no automatic renewal</p><ul><li>One credit per matching booking alert</li><li>Saving a preference uses no credits</li><li>Credits appear after payment verification</li></ul><button className="button primary wide" disabled={!data?.ready||!data?.verified||busy} onClick={buy}>{busy?'Opening checkout…':!data?.ready?'Paid alerts coming soon':!data?.verified?'Verify email to purchase':'Buy alert pass'}</button>{data?.ready&&!data?.verified&&<Link href="/settings">Open account settings →</Link>}</article></div><p className="small">{data?.ready?'Live booking monitoring is enabled.':'Paid alerts open when live monitoring and payments are available.'} Alerts do not reserve seats or guarantee availability. Browser push depends on your device settings; delivered alerts remain in your Notifications.</p>{!!data?.orders.length&&<><h2>Purchase history</h2><table className="billing-orders"><thead><tr><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.orders.map((order:any)=><tr key={order.order_id}><td>{new Date(order.created_at).toLocaleDateString('en-IN')}</td><td>₹{(order.amount/100).toFixed(2)}</td><td>{order.status}</td></tr>)}</tbody></table></>}</section>;
}
