'use client';
import {useState} from 'react';
import Link from './app-link';
import {api,useLoad} from './client-data';
import CommunityReviews from './community-reviews';
import {subscriptionPlans,billingPeriods,planPrice,periodLabels,type BillingPeriod} from '@/lib/subscription-plans';
function MembershipForm({subscription,preferences,onSaved}:{subscription:any;preferences:any;onSaved:()=>void}){
 const[active,setActive]=useState(!!subscription?.active),[tickets,setTickets]=useState(subscription?.ticket_updates!==0),[community,setCommunity]=useState(subscription?.community_updates!==0),[plan,setPlan]=useState(preferences?.selected_plan||'free'),[period,setPeriod]=useState<BillingPeriod>(preferences?.billing_period||'quarterly'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(next:boolean){setBusy(true);try{await api('subscriptions',{active:next,ticketUpdates:tickets,communityUpdates:community,selectedPlan:plan,billingPeriod:period});setActive(next);setMessage(next?(plan==='free'?'Your free subscription is active.':'Your plan choice is saved. Your account stays on free access until paid plans launch. No payment was taken.'):'Subscription updates cancelled. Your saved plan choice and film diary remain available.');onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <><p className="lede">Choose a plan for your movie life.</p><p className="small">Launch pricing preview. Struck-through amounts are proposed standard prices, not previous selling prices. Features stay the same across billing periods. Selecting a plan saves your preference; no payment or paid renewal starts.</p><div className="billing-periods" role="group" aria-label="Billing period">{billingPeriods.map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p==='half-yearly'?'Half-Yearly':p[0].toUpperCase()+p.slice(1)}</button>)}</div><div className="subscription-plan-grid">{subscriptionPlans.map(p=><article key={p.id} className={'panel subscription-plan '+(plan===p.id?'selected':'')}><p className="eyebrow">{p.name}</p><h2>{p.description}</h2><div className="plan-pricing"><p className="plan-price">₹{planPrice(p,period).price}<small>/ {periodLabels[period]}</small></p>{p.id!=='free'?<><p className="plan-standard"><span>Standard preview </span><s>₹{planPrice(p,period).standard}</s></p><span className="plan-saving">Save ₹{planPrice(p,period).savings}</span><small>Launch preview price</small></>:<p className="small">Always free · no renewal charges</p>}</div><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><button className={'button '+(plan===p.id?'primary':'secondary')} aria-pressed={plan===p.id} onClick={()=>setPlan(p.id)}>{plan===p.id?'Selected':'Choose '+p.name}</button></article>)}</div><article className="panel subscription-controls"><h2>Manage subscription</h2><p>{active?'Free membership updates are active.':'Membership updates are off.'}</p><fieldset disabled={busy}><legend>What would you like to hear about?</legend><label className="check-label"><input type="checkbox" checked={tickets} onChange={e=>setTickets(e.target.checked)}/>New approved tickets in my languages</label><label className="check-label"><input type="checkbox" checked={community} onChange={e=>setCommunity(e.target.checked)}/>Community updates from the team</label></fieldset><div className="actions"><button className="button primary" disabled={busy} onClick={()=>save(true)}>{busy?'Saving…':'Save plan & preferences'}</button>{active&&<button className="text-button" disabled={busy} onClick={()=>save(false)}>Cancel subscription updates</button>}</div>{message&&<p role="status">{message}</p>}</article></>;
}
export default function AlertPlans(){const[revision,refresh]=useState(0);const{data,error}=useLoad('subscriptions',revision);return <section className="section"><p className="eyebrow">MEMBERSHIP</p><h1>Your subscription.</h1><p><Link href="#community-reviews" className="text-button">Read community reviews ↓</Link></p>{error&&<p className="notice error">{error}</p>}{data?<MembershipForm subscription={data.subscription} preferences={data.preferences} onSaved={()=>refresh(n=>n+1)}/>:!error&&<p>Loading your membership…</p>}<CommunityReviews/></section>;}
