'use client';
import {useState} from 'react';
import {pictureCollections,pictureCatalog,collectionLabels,picturePath,visiblePicture,type PictureCollection,type Picture} from '@/lib/profile-pictures';
import {api,useLoad} from './client-data';
import {useSession} from './session-provider';
type Suggestion=Picture&{reason?:string};
function PictureChoices({value,onChange,suggestions,loading=false}:{value:string;onChange:(value:string)=>void;suggestions?:Suggestion[];loading?:boolean}){
 const[collection,setCollection]=useState<PictureCollection|'all'|'suggested'|''>(suggestions!==undefined?'suggested':value?'all':'');
 const choices:Suggestion[]=collection==='suggested'?suggestions||[]:collection==='all'?pictureCatalog:pictureCatalog.filter(p=>collection!==''&&(pictureCollections[collection] as readonly string[]).includes(p.file));
 function random(files:Suggestion[]){if(files.length)onChange(picturePath(files[crypto.getRandomValues(new Uint32Array(1))[0]%files.length].file));}
 return <div className="picture-choices"><div className="picture-category-tabs" role="group" aria-label="Picture categories">{(['cartoons','anime','animation','heroes'] as const).map(key=><button type="button" key={key} aria-pressed={collection===key} onClick={()=>setCollection(key)}>{collectionLabels[key]}</button>)}</div><label>Picture collection<select value={collection} onChange={e=>{const group=e.target.value as typeof collection;setCollection(group);if(group==='')onChange('');}}><option value="">Use my initials</option>{suggestions!==undefined&&<option value="suggested">For your film taste</option>}<option value="all">All pictures</option>{Object.keys(pictureCollections).map(key=><option key={key} value={key}>{collectionLabels[key as PictureCollection]}</option>)}</select></label>{collection&&<>{collection==='suggested'&&<p className="small">Suggestions use your saved languages and films you like. You can choose any picture.</p>}{loading&&collection==='suggested'?<p role="status">Finding pictures for your interests…</p>:<><div className="picture-options" role="group" aria-label="Choose a profile picture">{choices.map(p=><button type="button" key={p.file} aria-pressed={value===picturePath(p.file)} aria-label={p.label+(p.reason?' · '+p.reason:'')} title={p.reason||p.label} onClick={()=>onChange(picturePath(p.file))}><img src={picturePath(p.file)} alt="" loading="lazy"/><span className="picture-caption">{p.label}</span></button>)}</div>{choices.length?<button className="text-button" type="button" onClick={()=>random(choices)}>Pick randomly</button>:<p className="small">Choose All pictures, or save your languages and like some films for suggestions.</p>}</>}</>}</div>;
}
export function SignupAvatar(){const[value,setValue]=useState('');return <details className="signup-avatar"><summary>Choose a profile picture · optional</summary><PictureChoices value={value} onChange={setValue}/><input type="hidden" name="profilePicture" value={value}/><p className="small">Choose a picture, pick randomly from a collection, or keep your initials.</p></details>;}
export default function AvatarEditor({current}:{current:string}){
 const[value,setValue]=useState(()=>visiblePicture(current)),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const{reload}=useSession();const{data,error}=useLoad('me/picture');
 async function save(){setBusy(true);setMessage('');try{await api('me/picture',{picture:value});reload();setMessage('Profile picture saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="panel avatar-editor"><h2>Profile picture</h2>{value&&<img className="avatar" src={value} alt="Selected profile picture"/>}<PictureChoices value={value} onChange={setValue} suggestions={data?.suggestions||[]} loading={!data&&!error}/>{error&&<p className="small" role="status">Suggestions could not load. You can still browse all pictures.</p>}<button type="button" className="button secondary" onClick={save} disabled={busy}>{busy?'Saving…':'Save profile picture'}</button>{message&&<p role="status">{message}</p>}</div>;
}
