'use client';
import {useRef, useState, type FormEvent} from 'react';
import {HelpCircle, Search, ArrowRight, Star, CheckCircle2} from 'lucide-react';
import Link from './app-link';
import {api} from './client-data';

export const helpRoutes = ['help', 'report', 'contact', 'rate', 'about', 'terms', 'privacy'];
const questions = [
  {group: 'Account', question: 'How do I choose a username?', answer: 'Your name is used to suggest a username. If someone already uses it, we suggest an available variation. You can choose another before saving. Your display name and @username are separate.', href: '/settings', action: 'Edit your profile'},
  {group: 'Account', question: 'Can I change my username?', answer: 'Yes. Open Settings, change your username and save your profile. Your tickets, diary and conversations stay with your account. Your profile link changes when your username changes.', href: '/settings', action: 'Open Settings'},
  {group: 'Account', question: 'I cannot sign in. What should I do?', answer: 'Use the email or username you registered with. If you forgot your password, request a reset. When Google finds an existing email account, you may need to confirm your FrameFinder password to link it.', href: '/forgot-password', action: 'Reset password'},
  {group: 'Tickets', question: 'What does my ticket status mean?', answer: 'Awaiting review means your booking proof is waiting to be checked. Admin approved means the proof has been reviewed. Verified by issuer means the ticketing partner has confirmed it can be transferred. Check My Tickets for the latest status and any instructions.', href: '/my-tickets', action: 'Check My Tickets'},
  {group: 'Tickets', question: 'Why does my booking proof fail to upload?', answer: 'Upload a JPG, PNG or WebP image smaller than 4 MB. PDFs are not accepted by the current upload form. Check your connection and keep the original booking details readable. If it still fails, report the error without posting your booking proof publicly.', href: '/report', action: 'Report an upload issue'},
  {group: 'Tickets', question: 'What if my ticket is rejected or needs new proof?', answer: 'Open the review notification to go to your ticket. Read the reviewer’s instructions, choose Upload corrected proof and submit a new image. The ticket returns to the review queue. You can also reach it through My Tickets, under Selling.', href: '/my-tickets', action: 'Open My Tickets'},
  {group: 'Alerts', question: 'Does the alert pass renew automatically?', answer: 'No. The Alert Pass is a one-time purchase of booking-alert credits. One credit is used for each matching alert added to your Notifications. Saving a preference uses no credits. Check Alert Plans for your balance, price and purchase history.', href: '/subscriptions', action: 'View Alert Plans'},
  {group: 'Tickets', question: 'Where can I find my submitted tickets?', answer: 'Open your profile menu and choose My Tickets. It shows your submissions and purchases. Ticket Exchange shows published listings available for enquiries.', href: '/my-tickets', action: 'Open My Tickets'},
  {group: 'Tickets', question: 'Does accepting an offer book or transfer a ticket?', answer: 'No. Accepting an offer records an agreed price in the conversation. It does not reserve, verify or transfer the ticket. Only use checkout when it is available on the listing; transfer depends on the issuer and connected ticketing partner.', href: '/tickets', action: 'Open Ticket Exchange'},
  {group: 'Alerts', question: 'Why have I not received a booking or seat alert?', answer: 'Check the movie, theater, dates, language and format on your alert. Alerts require a matching update from connected monitoring. They do not guarantee availability. Check Notifications and enable browser notifications in Settings; if you use email alerts, check your spam folder too.', href: '/notifications', action: 'Check Notifications'},
  {group: 'Alerts', question: 'What should I check before opening a booking link?', answer: 'Confirm the show date, time, theater, language and format on the booking provider’s page before paying. Availability can change after an alert. A booking or payment problem on that provider’s page should also be raised with the provider.', href: '/booking-alerts', action: 'Review Booking Alerts'},
  {group: 'Messages', question: 'How are my conversations organised?', answer: 'Ticket conversations are grouped by movie. Use the unread and closed filters to find a chat, then open a conversation to discuss the ticket or make an offer. Notification updates have their own page.', href: '/messages', action: 'Open Messages'},
  {group: 'Privacy', question: 'Who can see my booking proof and profile?', answer: 'Your member profile, film activity and published listing details can be seen by other members. Booking proof is restricted to its owner and authorised review access. Ticket chat is available to its participants. See the privacy page for more detail.', href: '/privacy', action: 'Read Privacy Policy'},
];

function FeedbackForm({kind, signedIn}: {kind: 'contact' | 'report' | 'rating'; signedIn: boolean}) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [submitted, setSubmitted] = useState(false);
  const id = useRef('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError('');
    const form = new FormData(event.currentTarget);
    if (!id.current) id.current = crypto.randomUUID();
    try {
      await api('feedback', {id: id.current, kind, category: form.get('category') || 'feedback', message: form.get('message') || '', ...(kind === 'rating' ? {rating: Number(form.get('rating'))} : {})});
      setSubmitted(true);
    } catch (error) {setError((error as Error).message);} finally {setBusy(false);}
  }
  if (!signedIn) return <div className="panel"><h2>Send it from your account.</h2><p>Sign in to send a private {kind === 'rating' ? 'rating' : 'message'} to the FrameFinder team.</p><Link href="/login" className="button primary">Sign in <ArrowRight size={17}/></Link><p><Link href="/forgot-password">Trouble signing in? Reset your password</Link></p></div>;
  if (submitted) return <div className="panel feedback-success" role="status"><CheckCircle2 size={30}/><h2>{kind === 'rating' ? 'Thanks for your rating!' : 'Message sent.'}</h2><p>{kind === 'rating' ? 'Thanks for helping us improve FrameFinder.' : 'The team will review your message.'}</p><Link href="/help" className="button secondary">Back to Help</Link></div>;
  return <form className="panel support-form" onSubmit={submit} onChange={() => {id.current = '';}}>
    {kind === 'rating' ? <fieldset className="rating-choice"><legend>How was your experience?</legend>{[1,2,3,4,5].map(n => <label key={n}><input type="radio" name="rating" value={n} required/><span><Star size={19}/>{n}<span className="sr-only"> out of 5</span></span></label>)}</fieldset> : <label>What is this about?<select name="category" defaultValue={kind === 'contact' ? 'general' : 'booking'}><option value="general">General enquiry</option><option value="account">Account or sign-in</option><option value="upload">Booking proof upload</option><option value="booking">Booking or ticket error</option><option value="notifications">Notifications or alerts</option><option value="listing">Suspicious listing</option><option value="privacy">Privacy request</option></select></label>}
    <label>{kind === 'rating' ? 'Anything you would change? (optional)' : kind === 'contact' ? 'Your message' : 'Tell us what happened'}<textarea name="message" rows={6} required={kind !== 'rating'} minLength={kind === 'rating' ? undefined : 10} maxLength={2000} placeholder={kind === 'rating' ? 'What worked, and what could be better?' : kind === 'contact' ? 'Ask a question or tell us what you have in mind.' : 'Include the page, error message and steps that led to the problem.'}/></label>
    <p className="small">Do not include passwords, OTPs, payment details or booking QR codes. This message is shared privately with the site team.</p>
    <button className="button primary" disabled={busy}>{busy ? 'Saving…' : kind === 'rating' ? 'Submit rating' : 'Send message'}<ArrowRight size={17}/></button>
    {error && <p className="notice error" role="alert">{error}</p>}
  </form>;
}

export default function HelpPage({route, signedIn}: {route: string; signedIn: boolean}) {
  const [query, setQuery] = useState('');
  const titles: Record<string, string> = {help: 'A little help, right here.', report: 'Something not working?', contact: 'Talk to FrameFinder.', rate: 'Rate FrameFinder', about: 'About FrameFinder', terms: 'Terms & Conditions', privacy: 'Privacy Policy'};
  const shown = questions.filter(q => (q.question + q.answer + q.group).toLowerCase().includes(query.toLowerCase().trim()));
  return <section className="section help-page"><Link href="/" className="back-link">← Home</Link><p className="eyebrow">{route === 'help' ? 'HELP & FREQUENTLY ASKED QUESTIONS' : 'FRAMEFINDER'}</p><h1>{titles[route]}</h1>
    {route === 'help' && <><p className="lede">Accounts, tickets, alerts and conversations.</p><div className="searchbox help-search"><Search size={19}/><input aria-label="Search help" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search questions or an error…"/></div><div className="faq-list">{shown.map((q, i) => <details key={q.question}><summary><span className="faq-number">{i + 1}</span><span><small>{q.group}</small>{q.question}</span><span className="faq-plus" aria-hidden="true">+</span></summary><div className="faq-answer"><p>{q.answer}</p><Link href={q.href}>{q.action} →</Link></div></details>)}</div>{!shown.length && <p role="status">No matching questions. Try another word or report the problem.</p>}<div className="help-contact"><HelpCircle size={24}/><div><h2>Still need a hand?</h2><p>Tell us which page you were using and what went wrong.</p></div><Link href="/contact" className="button secondary">Contact Us</Link></div></>}
    {['contact','report','rate'].includes(route) && <><p className="lede">{route === 'rate' ? 'How was your experience?' : route === 'contact' ? 'Questions, suggestions or a general enquiry? Get in touch.' : 'Describe what went wrong so we can look into it. For payments made on another booking website, contact that provider too.'}</p><FeedbackForm key={route} kind={route === 'rate' ? 'rating' : route as 'contact' | 'report'} signedIn={signedIn}/></>}
    {route === 'about' && <div className="panel prose"><p>FrameFinder brings film discovery, a personal watch diary and ticket conversations into one place.</p><h2>Discover and track films</h2><p>Save films, track what you watch and share your ratings and reviews. For You uses your film activity and language preferences to suggest what to watch next.</p><h2>Connect with film fans</h2><p>Follow members, see their film activity and discover recommendations through people who share your interests.</p><h2>Manage ticket plans</h2><p>Browse published listings, discuss tickets in private conversations and manage your submissions from My Tickets. Availability monitoring, checkout and issuer transfers depend on connected services.</p><Link href="/contact" className="button secondary">Contact the team <ArrowRight size={17}/></Link></div>}
    {route === 'terms' && <article className="panel prose"><p>These terms describe the use of FrameFinder’s film, community and ticket features.</p><h2>Your account and content</h2><p>Provide accurate account details and keep your sign-in credentials private. Post only content and booking proof you are entitled to share. Do not impersonate someone, harass members, submit duplicate or false listings, or misuse the service.</p><h2>Ticket listings and offers</h2><p>Only list tickets you own. Published listings, admin approval and accepted offers do not guarantee ticket validity, reservation or transfer. Issuer rules and the available checkout flow determine whether a transfer can be completed. Review the listing and provider’s conditions before paying.</p><h2>Alerts and external services</h2><p>Alerts depend on connected monitoring and delivery services. Delivery and seat availability are not guaranteed. Check show details and prices directly with the booking provider. The provider handles bookings and payments made on its own website.</p><h2>Moderation and issues</h2><p>FrameFinder may reject misleading listings and restrict abusive activity. Use Report a Problem to flag an issue or contact the team about a review decision.</p><h2>Questions</h2><p><Link href="/contact">Contact the team</Link> about these terms. Read the <Link href="/privacy">Privacy Policy</Link> for information about account and activity data.</p></article>}
    {route === 'privacy' && <article className="panel prose"><p>This page describes the data used by FrameFinder’s current features.</p><h2>Account and film activity</h2><p>FrameFinder stores your email, username, display name, profile details and film activity. Email signup stores a password hash. Google sign-in supplies your verified email, name and Google account identifier. Your languages, ratings and saved film activity support recommendations.</p><h2>What other members can see</h2><p>Members can see profile details, public film activity, reviews and follow connections. Published ticket listings show information such as the seller’s username, film, theater, show and price. Your login email is not included in public member profiles.</p><h2>Tickets, messages and support</h2><p>Booking proof is kept in private storage with access checks for the owner and authorised administrators. A one-way booking reference fingerprint helps detect duplicates. Ticket conversations and offers are available to their participants. Support messages and ratings are stored for the site team to review; they are not public reviews.</p><h2>Sessions, notifications and providers</h2><p>A session cookie keeps you signed in. If you enable browser notifications, FrameFinder stores the subscription information needed to send them. Configured providers process data needed for hosting, storage, sign-in, movie information, notification delivery and enabled payment or ticket services.</p><h2>Your choices</h2><p>Edit profile information and notification preferences in Settings. You can unsend your own chat messages through the conversation controls. Contact the team to request help with access, correction or deletion of stored data. Some transaction or security records may require separate handling.</p><Link href="/contact" className="button secondary">Ask a privacy question <ArrowRight size={17}/></Link></article>}
  </section>;
}
