 'use client';
import {useEffect,useState} from 'react';
import ProfilePhoto from './profile-photo';
import {Bell} from 'lucide-react';
import Link from './app-link';
import {api,useLoad} from './client-data';
export async function detachPush(){if(!('serviceWorker' in navigator))return;const reg=await navigator.serviceWorker.getRegistration('/');const sub=await reg?.pushManager.getSubscription();if(sub){await api('notifications/push',{endpoint:sub.endpoint},'DELETE');await sub.unsubscribe();}}
export function PushSettings({onEnabled}:{onEnabled?:()=>Promise<void>}={}){const[status,setStatus]=useState(''),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{if(!('serviceWorker' in navigator)||!('PushManager' in window)){setStatus('Browser notifications are not supported on this device. Try Chrome on Android.');return;}navigator.serviceWorker.getRegistration('/').then(r=>r?.pushManager.getSubscription()).then(s=>setEnabled(!!s)).catch(()=>setStatus('Could not check this device.'));},[]);
 async function enable(){setBusy(true);try{if(!('Notification' in window)||!('serviceWorker' in navigator)||!('PushManager' in window))throw new Error('Use a browser with push support, such as Chrome on Android.');const permission=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;if(permission!=='granted')throw new Error('Allow notifications in Chrome site settings to enable mobile alerts.');const config=await api('notifications/push');if(!config.publicKey)throw new Error('Browser notification setup is pending on the server.');const registration=await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready;const binary=atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/'));const key=Uint8Array.from(binary,c=>c.charCodeAt(0));const sub=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await api('notifications/push',sub.toJSON());setEnabled(true);setStatus('Enabled on this device for followers, messages, offers and matching show alerts.');await onEnabled?.();}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 return <div className="panel push-settings"><Bell/><div><h2>Notifications on your phone</h2><p>Get Chrome notifications for new followers, conversations, offers and matching booking or seat alerts.</p><button className="button secondary" disabled={busy} onClick={enabled?async()=>{setBusy(true);try{await detachPush();setEnabled(false);setStatus('Disabled on this device.');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}:enable}>{busy?'Please wait…':enabled?'Disable on this device':'Enable browser notifications'}</button>{status&&<p role="status">{status}</p>}<small>Show alerts need the monitoring feed to be running. Notification delivery also depends on your device and browser settings.</small></div></div>;
}
export default function NotificationCenter(){const[revision,refresh]=useState(0),[err,setErr]=useState('');const{data,error}=useLoad('notifications',revision);useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)refresh(n=>n+1);},15000);return()=>clearInterval(timer);},[]);async function read(id?:string){try{await api('notifications/read',id?{id}:{});refresh(n=>n+1);window.dispatchEvent(new Event('ff-inbox-changed'));}catch(e){setErr((e as Error).message);}}
 return <section className="section"><p className="eyebrow">YOUR FILM LIFE, UP TO DATE</p><div className="section-heading"><h1>Notifications.</h1><button className="button secondary" onClick={()=>read()}>Mark all read</button></div>{(error||err)&&<p className="notice error">{error||err}</p>}{data?.notifications.map((n:any)=><div className={'notification '+(!n.read?'unread':'')} key={n.id}><ProfilePhoto name={n.sender_name} src={n.sender_avatar}/><div><Link href={n.link} onClick={()=>{void read(n.id);}}><h3>{n.title}</h3><p>{n.message}</p></Link><small>{new Date(n.created_at).toLocaleString()}</small></div>{!n.read&&<button className="text-button" onClick={()=>read(n.id)}>Mark read</button>}</div>)}{data&&!data.notifications.length&&<div className="empty"><h2>You're all caught up.</h2><p>Your followers, messages, offers and show alerts will appear here.</p></div>}</section>;
}

export function NotificationSetup(){const[done,setDone]=useState(false),[error,setError]=useState('');const{data}=useLoad('notifications/setup');useEffect(()=>{if(data?.prompted)location.replace('/for-you');},[data]);async function continueToFilms(){try{await api('notifications/setup',{});setDone(true);location.assign('/for-you');}catch(e){setError((e as Error).message);}}return <section className="section onboarding"><p className="eyebrow">ONE LAST CHOICE</p><h1>Stay in the loop.</h1><p>Choose whether this device can notify you. You can change this anytime in Settings.</p>{data&&!data.prompted&&<PushSettings onEnabled={continueToFilms}/>}<button className="button primary" disabled={done} onClick={continueToFilms}>Continue to my films</button><button className="text-button" disabled={done} onClick={continueToFilms}>Not now</button>{error&&<p role="alert">{error}</p>}</section>;}
