'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {Search,X} from 'lucide-react';
import Link,{navigate} from './app-link';
import {api,useDebounced} from './client-data';
import ProfilePhoto from './profile-photo';
export default function PeopleSearch({route}:{route:string}){
 const[q,setQ]=useState(''),[open,setOpen]=useState(false),[members,setMembers]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[active,setActive]=useState(-1);const query=useDebounced(q.trim(),300),id=useId(),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{setOpen(false);setQ('');setMembers([]);},[route]);
 useEffect(()=>{const focus=()=>{input.current?.focus();setOpen(true);};window.addEventListener('ff-find-people',focus);return()=>window.removeEventListener('ff-find-people',focus);},[]);
 useEffect(()=>{let current=true;setActive(-1);setMembers([]);setError('');if(!query){setLoading(false);return;}setLoading(true);api('members?q='+encodeURIComponent(query)).then(data=>{if(current)setMembers(data.members.slice(0,8));}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false};},[query]);
 const ready=q.trim()===query;const shown=open&&!!q.trim();
 return <div className="people-search" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><form className="people-search-field" role="search" onSubmit={e=>{e.preventDefault();setOpen(true);input.current?.focus();if(ready&&members.length)navigate('/members/'+members[Math.max(0,active)].username);}}><button type="submit" aria-label="Search people"><Search size={20}/></button><input ref={input} placeholder="Search people…" aria-label="Search people by name or username" role="combobox" aria-autocomplete="list" aria-expanded={shown} aria-controls={id} aria-activedescendant={active>=0?id+'-'+active:undefined} autoComplete="off" value={q} onFocus={()=>setOpen(true)} onChange={e=>{setQ(e.target.value);setOpen(true);setActive(-1);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setActive(-1);}if(['ArrowDown','ArrowUp'].includes(e.key)&&ready&&members.length){e.preventDefault();setOpen(true);setActive(i=>e.key==='ArrowDown'?Math.min(i+1,members.length-1):Math.max(i-1,0));}}}/>{q&&<button type="button" aria-label="Clear people search" onClick={()=>{setQ('');input.current?.focus();}}><X size={17}/></button>}</form>{shown&&<div className="people-search-results"><div id={id} role="listbox" aria-label="People">{ready&&members.map((member,i)=><Link id={id+'-'+i} role="option" aria-selected={active===i} key={member.id} href={'/members/'+member.username} onClick={()=>setOpen(false)}><ProfilePhoto name={member.name} src={member.avatar}/><span><strong>{member.name}</strong><small>@{member.username}</small></span></Link>)}</div>{(loading||!ready)&&<p role="status">Searching…</p>}{error&&<p role="alert">{error}</p>}{ready&&!loading&&!error&&!members.length&&<p role="status">No people found.</p>}</div>}</div>;
}
