import {manageMembers} from './member-management';
import {z} from 'zod';
import {all,one,run,batch,setting,getAsset} from '@/lib/platform';
import {user,ApiError,body,now,limit,cookie,hash,type Account} from './security';
import {notify} from './notifications';
export const isAdmin=(a:Account)=>setting('ADMIN_USER_IDS').split(',').map(s=>s.trim()).filter(Boolean).includes(a.id);
export async function admin(req:Request,path:string[]){const a=(await user(req))!;if(!isAdmin(a))throw new ApiError(403,'This account is not an administrator.');
 if(path[1]==='members')return manageMembers(req,a.id);
 if(path[1]==='access'){
  const session=cookie(req,'ff_session'),key=hash('admin-access:'+session);
  if(req.method==='POST'){await run("INSERT OR REPLACE INTO auth_tokens(token,user_id,purpose,expires) SELECT ?,?,'admin-access',expires FROM sessions WHERE token=? AND user_id=? AND expires>?",[key,a.id,hash(session),a.id,now()]);return Response.json({verified:true});}
  if(req.method==='GET')return Response.json({verified:!!await one('SELECT token FROM auth_tokens WHERE token=? AND user_id=? AND purpose=? AND expires>?',[key,a.id,'admin-access',now()])});
  throw new ApiError(405,'Method not allowed');
 }
 if(req.method==='GET'&&path[1]==='proof'){const t=await one<any>('SELECT proof_id FROM tickets WHERE id=?',[path[2]]);if(!t)throw new ApiError(404,'Listing not found');const asset=await getAsset(t.proof_id);if(!asset)throw new ApiError(404,'Proof unavailable');return new Response(asset.body,{headers:{'Content-Type':asset.mime,'Cache-Control':'no-store'}});}
 if(req.method==='GET')return Response.json({tickets:await all("SELECT t.id,t.movie,t.theater,t.show_at,t.status,t.price,t.face_value,t.proof_id,a.username,r.decision,r.note FROM tickets t JOIN accounts a ON a.id=t.seller_id LEFT JOIN admin_reviews r ON r.id=(SELECT id FROM admin_reviews WHERE ticket_id=t.id ORDER BY created_at DESC,id DESC LIMIT 1) WHERE t.status='pending_verification' AND t.review_pending=1 AND t.show_at>? ORDER BY t.created_at DESC LIMIT 100",[now()]),members:await all('SELECT id,username,name FROM accounts WHERE NOT EXISTS(SELECT 1 FROM removed_accounts WHERE user_id=accounts.id) ORDER BY username LIMIT 500'),feedback:await all('SELECT f.*,a.username FROM member_feedback f JOIN accounts a ON a.id=f.user_id ORDER BY f.status,f.created_at DESC LIMIT 100')});
 if(req.method!=='POST')throw new ApiError(405,'Method not allowed');await limit('admin:'+a.id,30,60);
 if(path[1]==='feedback'){const p=z.object({id:z.string().uuid(),status:z.enum(['open','resolved'])}).parse(await body(req));const result=await run('UPDATE member_feedback SET status=? WHERE id=?',[p.status,p.id]);if(!result.changes)throw new ApiError(404,'Feedback not found');return Response.json({ok:true});}
 if(path[1]==='review'){const p=z.object({ticketId:z.string().uuid(),decision:z.enum(['approved','rejected','needs_info']),note:z.string().trim().min(5).max(1000),proofId:z.string().uuid()}).parse(await body(req));const t=await one<any>('SELECT * FROM tickets WHERE id=?',[p.ticketId]);if(!t)throw new ApiError(404,'Listing not found');if(t.seller_id===a.id)throw new ApiError(403,'Another administrator must review your own listing.');if(t.status!=='pending_verification'||!t.review_pending||p.proofId!==t.proof_id)throw new ApiError(409,'Only pending listings can be reviewed.');const id=crypto.randomUUID();await batch([{sql:'INSERT INTO admin_reviews(id,ticket_id,admin_id,decision,note,created_at,proof_id) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM tickets WHERE id=? AND proof_id=? AND review_pending=1 AND status=?)',args:[id,t.id,a.id,p.decision,p.note,now(),t.proof_id,t.id,t.proof_id,'pending_verification']},{sql:"UPDATE tickets SET review_pending=0,status=CASE WHEN ?='rejected' THEN 'rejected' ELSE status END,is_public=CASE WHEN ? IN ('rejected','needs_info') THEN 0 ELSE is_public END WHERE id=? AND EXISTS(SELECT 1 FROM admin_reviews WHERE id=?)",args:[p.decision,p.decision,t.id,id]}]);if(!await one('SELECT id FROM admin_reviews WHERE id=?',[id]))throw new ApiError(409,'This submission has already been reviewed. Refresh the queue.');const correction=p.decision==='approved'?'':' Open your ticket and upload corrected booking proof to submit it again.';await notify('review:'+id,t.seller_id,p.decision==='approved'?'Booking proof approved':p.decision==='rejected'?'Ticket rejected — upload corrected proof':'New booking proof requested',p.note+correction,'/tickets/'+t.id);return Response.json({ok:true});}
 if(path[1]==='notify'){const p=z.object({userId:z.string().min(1),title:z.string().trim().min(1).max(100),message:z.string().trim().min(1).max(1000)}).parse(await body(req));if(!await one('SELECT id FROM accounts WHERE id=?',[p.userId]))throw new ApiError(404,'Member not found');await notify('admin:'+crypto.randomUUID(),p.userId,p.title,p.message,'/notifications');return Response.json({ok:true});}
 throw new ApiError(404,'Not found');
}
