import {recipientSearch,sendAdminNotice} from './admin-notices';
import {ticketSubscriberNotice} from './subscriptions';
import {manageMembers} from './member-management';
import {z} from 'zod';
import {all,one,run,batch,setting,getAsset} from '@/lib/platform';
import {user,ApiError,body,now,limit,cookie,hash,type Account} from './security';
import {notify} from './notifications';
export const isAdmin=(a:Account)=>setting('ADMIN_USER_IDS').split(',').map(s=>s.trim()).filter(Boolean).includes(a.id);
export async function admin(req:Request,path:string[]){const a=(await user(req))!;if(!isAdmin(a))throw new ApiError(403,'This account is not an administrator.');
 if(path[1]==='recipients'&&req.method==='GET')return recipientSearch(req);
 if(path[1]==='notify'&&req.method==='POST')return sendAdminNotice(req,a.id);
 if(path[1]==='publish-feedback'&&req.method==='POST'){const p=z.object({id:z.string().uuid(),publish:z.boolean()}).strict().parse(await body(req));await limit('publish-feedback:'+a.id,30,60);const changed=await run("UPDATE feedback_publication SET published=? WHERE feedback_id=? AND consent=1 AND EXISTS(SELECT 1 FROM member_feedback WHERE id=feedback_id AND kind='rating' AND rating>=4)",[+p.publish,p.id]);if(!changed.changes)throw new ApiError(400,'Only opted-in ratings of four stars or more can be featured.');return Response.json({ok:true});}
 if(path[1]==='subscriptions'&&req.method==='GET')return Response.json({members:await all('SELECT a.id,a.name,a.username,s.active,s.ticket_updates,s.community_updates FROM member_subscriptions s JOIN accounts a ON a.id=s.user_id WHERE NOT EXISTS(SELECT 1 FROM removed_accounts WHERE user_id=a.id) ORDER BY s.updated_at DESC LIMIT 100'),total:(await one<{n:number}>('SELECT COUNT(*) n FROM member_subscriptions s WHERE active=1 AND NOT EXISTS(SELECT 1 FROM removed_accounts WHERE user_id=s.user_id)'))?.n||0});
 if(path[1]==='members')return manageMembers(req,a.id);
 if(path[1]==='access'){if(!['GET','POST'].includes(req.method))throw new ApiError(405,'Method not allowed');return Response.json({verified:true});}
 if(req.method==='GET'&&path[1]==='proof'){const t=await one<any>('SELECT proof_id FROM tickets WHERE id=?',[path[2]]);if(!t)throw new ApiError(404,'Listing not found');const asset=await getAsset(t.proof_id);if(!asset)throw new ApiError(404,'Proof unavailable');return new Response(asset.body,{headers:{'Content-Type':asset.mime,'Cache-Control':'no-store'}});}
 if(req.method==='GET')return Response.json({tickets:await all("SELECT (t.seller_id != ?) AS can_review,t.id,t.movie,t.theater,t.show_at,t.status,t.price,t.face_value,t.proof_id,a.username,r.decision,r.note FROM tickets t JOIN accounts a ON a.id=t.seller_id LEFT JOIN admin_reviews r ON r.id=(SELECT id FROM admin_reviews WHERE ticket_id=t.id ORDER BY created_at DESC,id DESC LIMIT 1) WHERE t.status='pending_verification' AND t.review_pending=1 AND t.show_at>? ORDER BY t.created_at DESC LIMIT 100",[a.id,now()]),members:await all('SELECT id,username,name FROM accounts WHERE NOT EXISTS(SELECT 1 FROM removed_accounts WHERE user_id=accounts.id) ORDER BY username LIMIT 500'),feedback:await all('SELECT f.*,a.username,p.consent,p.published FROM member_feedback f JOIN accounts a ON a.id=f.user_id LEFT JOIN feedback_publication p ON p.feedback_id=f.id ORDER BY f.status,f.created_at DESC LIMIT 100')});
 if(req.method!=='POST')throw new ApiError(405,'Method not allowed');await limit('admin:'+a.id,30,60);
 if(path[1]==='feedback'){const p=z.object({id:z.string().uuid(),status:z.enum(['open','resolved'])}).parse(await body(req));const result=await run('UPDATE member_feedback SET status=? WHERE id=?',[p.status,p.id]);if(!result.changes)throw new ApiError(404,'Feedback not found');return Response.json({ok:true});}
 if(path[1]==='review'){const p=z.object({ticketId:z.string().uuid(),decision:z.enum(['approved','rejected','needs_info']),note:z.string().trim().min(5).max(1000),proofId:z.string().uuid()}).parse(await body(req));const t=await one<any>('SELECT * FROM tickets WHERE id=?',[p.ticketId]);if(!t)throw new ApiError(404,'Listing not found');if(t.seller_id===a.id)throw new ApiError(403,'Another administrator must review your own listing.');if(t.status!=='pending_verification'||!t.review_pending||p.proofId!==t.proof_id)throw new ApiError(409,'Only pending listings can be reviewed.');const id=crypto.randomUUID();await batch([{sql:'INSERT INTO admin_reviews(id,ticket_id,admin_id,decision,note,created_at,proof_id) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM tickets WHERE id=? AND proof_id=? AND review_pending=1 AND status=?)',args:[id,t.id,a.id,p.decision,p.note,now(),t.proof_id,t.id,t.proof_id,'pending_verification']},{sql:"UPDATE tickets SET review_pending=0,status=CASE WHEN ?='rejected' THEN 'rejected' ELSE status END,is_public=CASE WHEN ? IN ('rejected','needs_info') THEN 0 ELSE is_public END WHERE id=? AND EXISTS(SELECT 1 FROM admin_reviews WHERE id=?)",args:[p.decision,p.decision,t.id,id]}]);if(!await one('SELECT id FROM admin_reviews WHERE id=?',[id]))throw new ApiError(409,'This submission has already been reviewed. Refresh the queue.');const correction=p.decision==='approved'?'':' Open your ticket and upload corrected booking proof to submit it again.';if(p.decision==='approved')await ticketSubscriberNotice(t.id,t.proof_id);await notify('review:'+id,t.seller_id,p.decision==='approved'?'Booking proof approved':p.decision==='rejected'?'Ticket rejected — upload corrected proof':'New booking proof requested',p.note+correction,'/tickets/'+t.id);return Response.json({ok:true});}
 throw new ApiError(404,'Not found');
}
