import seed from '@/data/movies.json';
import {setting} from '@/lib/platform';
export type Film=typeof seed[number]&{tmdbId?:number};
export const catalog:Film[]=seed;
const byId=new Map(catalog.map(m=>[m.id,m]));
const codes:Record<string,string>={English:'en',Telugu:'te',Hindi:'hi',Tamil:'ta',Malayalam:'ml',Kannada:'kn',Korean:'ko',Japanese:'ja',French:'fr'};
const genreNames:Record<number,string>={28:'Action',12:'Adventure',16:'Animation',35:'Comedy',80:'Crime',99:'Documentary',18:'Drama',10751:'Family',14:'Fantasy',36:'History',27:'Horror',10402:'Music',9648:'Mystery',10749:'Romance',878:'Sci-fi',10770:'TV Movie',53:'Thriller',10752:'War',37:'Western'};
export async function tmdb(path:string,params:Record<string,string>={}){if(!setting('TMDB_READ_TOKEN'))return null;const url=new URL('https://api.themoviedb.org/3/'+path);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v));const r=await fetch(url,{headers:{Authorization:'Bearer '+setting('TMDB_READ_TOKEN')},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('Movie catalog provider is temporarily unavailable.');return r.json() as Promise<any>;}
function normalize(m:any):Film{return {id:1000000+m.id,tmdbId:m.id,title:m.title,year:Number((m.release_date||'').slice(0,4))||0,language:Object.entries(codes).find(([,v])=>v===m.original_language)?.[0]||m.original_language,minutes:m.runtime||0,genres:(m.genres?.map((g:any)=>g.name)||m.genre_ids?.map((id:number)=>genreNames[id])||[]).filter(Boolean),moods:[],description:m.overview||'',poster:m.poster_path?'https://image.tmdb.org/t/p/w500'+m.poster_path:'',source:'https://www.themoviedb.org/movie/'+m.id};}
export async function findFilm(id:number):Promise<Film|null>{const local=byId.get(id);if(local)return local;if(id<1000000)return null;const m=await tmdb('movie/'+(id-1000000));return m?normalize(m):null;}
export async function movies(url:URL){const q=(url.searchParams.get('q')||'').normalize('NFKC').trim().toLowerCase().slice(0,120),language=url.searchParams.get('language')||'',page=Math.min(500,Math.max(1,Number(url.searchParams.get('page'))||1)),genre=url.searchParams.get('genre')||'';
 if(setting('TMDB_READ_TOKEN')){const remote=await tmdb(q?'search/movie':'discover/movie',{page:String(page),include_adult:'false',...(q?{query:q}:{sort_by:'popularity.desc',...(language?{with_original_language:codes[language]||language}:{})})});let results=remote.results.map(normalize);if(q&&language)results=results.filter((m:Film)=>m.language===language);return {movies:results,total:remote.total_results,pages:Math.min(remote.total_pages,500),page,source:'TMDB'};}
 const filtered=catalog.filter(m=>(!q||m.title.toLowerCase().includes(q.toLowerCase()))&&(!language||m.language===language)&&(!genre||m.genres.includes(genre)));return {movies:filtered.slice((page-1)*24,page*24),total:filtered.length,pages:Math.ceil(filtered.length/24),page,source:'Included catalog'};
}
export async function providers(film:Film,region:string){let id=film.tmdbId;if(!id){const data=await tmdb('search/movie',{query:film.title,year:String(film.year)});id=data?.results?.find((x:any)=>x.title.toLowerCase()===film.title.toLowerCase())?.id;}if(!id)return {configured:!!setting('TMDB_READ_TOKEN'),providers:[],link:null,region};const data=await tmdb(`movie/${id}/watch/providers`);const entry=data?.results?.[region];return {configured:true,providers:['flatrate','rent','buy'].flatMap(type=>(entry?.[type]||[]).map((x:any)=>({name:x.provider_name,type,logo:'https://image.tmdb.org/t/p/w92'+x.logo_path}))),link:entry?.link||null,region,attribution:'Watch availability by JustWatch via TMDB'};}
