import {publicTicketSql} from './ticket-visibility';
import {z} from 'zod';
import {all,one,run,batch} from '@/lib/platform';
import {ApiError,user,body,now,hash,limit} from './security';
import {notify} from './notifications';
import {containsContactDetails,blockedMessage} from '@/lib/message-policy';
export async function chat(req:Request,path:string[]){const a=(await user(req))!;const url=new URL(req.url);
if(!path[1]){if(req.method==='GET')return Response.json({conversations:await all('SELECT c.*,EXISTS(SELECT 1 FROM removed_accounts WHERE user_id IN (c.buyer_id,c.seller_id)) participant_removed,t.movie,t.show_at,t.status AS ticket_status,(SELECT r.decision FROM admin_reviews r WHERE r.ticket_id=t.id AND r.proof_id=t.proof_id ORDER BY r.created_at DESC,r.id DESC LIMIT 1) review_decision,(SELECT COUNT(*) FROM notifications n WHERE n.user_id=? AND n.read=0 AND n.link=char(47,109,101,115,115,97,103,101,115,47)||c.id) unread,b.username AS buyer,s.username AS seller,b.name AS buyer_name,s.name AS seller_name,b.avatar AS buyer_avatar,s.avatar AS seller_avatar FROM conversations c JOIN tickets t ON t.id=c.ticket_id JOIN accounts b ON b.id=c.buyer_id JOIN accounts s ON s.id=c.seller_id WHERE c.buyer_id=? OR c.seller_id=? ORDER BY c.updated_at DESC LIMIT 100',[a.id,a.id,a.id]),viewerId:a.id});if(req.method!=='POST')throw new ApiError(405,'Method not allowed');const p=z.object({ticketId:z.string().uuid()}).parse(await body(req));await limit('new-chat:'+a.id,20);const t=await one<any>('SELECT * FROM tickets WHERE id=?',[p.ticketId]);if(!t||t.seller_id===a.id||!await one('SELECT t.id FROM tickets t WHERE t.id=? AND '+publicTicketSql,[t.id,now()]))throw new ApiError(404,'This listing is not available for enquiries.');const id=hash(t.id+':'+a.id);const created=await run('INSERT OR IGNORE INTO conversations(id,ticket_id,buyer_id,seller_id,created_at,updated_at) VALUES(?,?,?,?,?,?)',[id,t.id,a.id,t.seller_id,now(),now()]);if(created.changes)await notify('request:'+id,t.seller_id,'New message request',`${a.name} wants to discuss ${t.movie}.`,'/messages/'+id);return Response.json({id});}
const c=await one<any>('SELECT c.*,EXISTS(SELECT 1 FROM removed_accounts WHERE user_id IN (c.buyer_id,c.seller_id)) participant_removed,t.movie,t.theater,t.quantity,t.language,t.format,t.price,t.face_value,t.show_at,t.status AS ticket_status,(SELECT r.decision FROM admin_reviews r WHERE r.ticket_id=t.id AND r.proof_id=t.proof_id ORDER BY r.created_at DESC,r.id DESC LIMIT 1) review_decision,(SELECT COUNT(*) FROM notifications n WHERE n.user_id=? AND n.read=0 AND n.link=char(47,109,101,115,115,97,103,101,115,47)||c.id) unread,b.username AS buyer,s.username AS seller,b.name AS buyer_name,s.name AS seller_name,b.avatar AS buyer_avatar,s.avatar AS seller_avatar FROM conversations c JOIN tickets t ON t.id=c.ticket_id JOIN accounts b ON b.id=c.buyer_id JOIN accounts s ON s.id=c.seller_id WHERE c.id=? AND (c.buyer_id=? OR c.seller_id=?)',[a.id,path[1],a.id,a.id]);if(!c)throw new ApiError(404,'Conversation not found');
if(req.method==='GET'){const before=url.searchParams.get('before')||'9999';const messages=await all<any>('SELECT * FROM chat_messages WHERE conversation_id=? AND created_at<? ORDER BY created_at DESC,id DESC LIMIT 100',[c.id,before]);return Response.json({conversation:c,viewerId:a.id,messages:messages.reverse(),offers:await all('SELECT * FROM ticket_offers WHERE conversation_id=? ORDER BY created_at DESC LIMIT 50',[c.id]),hasOlder:messages.length===100});}
if(req.method==='DELETE'&&path[2]==='messages'&&path[3]){const deleted=await run('DELETE FROM chat_messages WHERE id=? AND conversation_id=? AND sender_id=?',[path[3],c.id,a.id]);if(!deleted.changes)throw new ApiError(404,'Your message was not found.');await run('DELETE FROM notifications WHERE id=?',['chat:'+path[3]]);return Response.json({ok:true});}
if(req.method!=='POST')throw new ApiError(405,'Method not allowed');if(c.participant_removed||!['pending_verification','verified'].includes(c.ticket_status)||c.show_at<=now())throw new ApiError(409,'This conversation is read-only because the listing is no longer open.');await limit('chat:'+a.id,60,60);const p=await body(req);
if(path[2]==='messages'){const m=z.object({message:z.string().trim().min(1).max(2000),nonce:z.string().uuid()}).parse(p);if(containsContactDetails(m.message))throw new ApiError(422,blockedMessage);const id=hash(c.id+':'+a.id+':'+m.nonce),stamp=now();const inserted=await run('INSERT OR IGNORE INTO chat_messages(id,conversation_id,sender_id,message,created_at) VALUES(?,?,?,?,?)',[id,c.id,a.id,m.message,stamp]);if(inserted.changes){await run('UPDATE conversations SET updated_at=? WHERE id=?',[stamp,c.id]);const recipient=c.buyer_id===a.id?c.seller_id:c.buyer_id;await notify('chat:'+id,recipient,'New private message',`${a.name} sent a message about ${c.movie}.`,'/messages/'+c.id);}return Response.json({ok:true});}
if(path[2]==='offers'&&!path[3]){const o=z.object({amount:z.number().int().positive().max(10000000),nonce:z.string().uuid().optional()}).parse(p);const id=o.nonce?hash(c.id+':'+a.id+':offer:'+o.nonce):crypto.randomUUID(),stamp=now();if(await one('SELECT id FROM ticket_offers WHERE id=?',[id]))return Response.json({id});await batch([{sql:"UPDATE ticket_offers SET status='superseded',updated_at=? WHERE conversation_id=? AND status IN ('pending','accepted')",args:[stamp,c.id]},{sql:'INSERT INTO ticket_offers(id,conversation_id,sender_id,amount,created_at,updated_at) VALUES(?,?,?,?,?,?)',args:[id,c.id,a.id,o.amount,stamp,stamp]},{sql:'UPDATE conversations SET updated_at=? WHERE id=?',args:[stamp,c.id]}]);const recipient=c.buyer_id===a.id?c.seller_id:c.buyer_id;await notify('offer:'+id,recipient,'New ticket offer',`${a.name} offered ₹${(o.amount/100).toFixed(2)} for ${c.movie}.`,'/messages/'+c.id);return Response.json({id});}
if(path[2]==='offers'&&path[3]){const action=z.enum(['accept','decline','withdraw']).parse(p.action);const offer=await one<any>('SELECT * FROM ticket_offers WHERE id=? AND conversation_id=?',[path[3],c.id]);if(!offer||offer.status!=='pending')throw new ApiError(409,'Offer is no longer pending.');if(action==='withdraw'?offer.sender_id!==a.id:offer.sender_id===a.id)throw new ApiError(403,'Only the other participant can accept or decline your offer.');const status={accept:'accepted',decline:'declined',withdraw:'withdrawn'}[action];const changed=await run("UPDATE ticket_offers SET status=?,updated_at=? WHERE id=? AND status='pending'",[status,now(),offer.id]);if(!changed.changes)throw new ApiError(409,'The offer changed. Refresh and try again.');await run('UPDATE conversations SET updated_at=? WHERE id=?',[now(),c.id]);await notify('offer-status:'+offer.id+':'+status,c.buyer_id===a.id?c.seller_id:c.buyer_id,'Offer '+status,`The offer for ${c.movie} was ${status}.`,'/messages/'+c.id);return Response.json({ok:true});}
throw new ApiError(404,'Not found');}
