import {notify} from './notifications';
import {z} from 'zod';
import {all,one,run,batch,setting,getAsset} from '@/lib/platform';
import {alertSchema,indiaToday,extractEventCode,theaters} from '@/lib/booking';
import {ApiError,user,body,now,hash,signed,safeEqual,limit} from './security';
type Order={order_id:string;user_id:string;amount:number;credits:number;payment_id:string|null;status:string};
async function razor(path:string,data?:unknown){const id=setting('RAZORPAY_KEY_ID'),secret=setting('RAZORPAY_KEY_SECRET');if(!id||!secret)throw new ApiError(503,'Payments are not connected yet.');const r=await fetch('https://api.razorpay.com/v1/'+path,{method:data?'POST':'GET',headers:{Authorization:'Basic '+Buffer.from(id+':'+secret).toString('base64'),'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new ApiError(502,'The payment provider could not complete this request.');return r.json() as Promise<any>;}
async function balance(id:string){const paid=await one<{n:number}>('SELECT COALESCE(SUM(credits),0) n FROM billing WHERE user_id=? AND status=?',[id,'paid']);const used=await one<{n:number}>('SELECT COUNT(*) n FROM credit_uses WHERE user_id=?',[id]);return Math.max(0,3+(paid?.n||0)-(used?.n||0));}
async function grant(order:Order,paymentId:string){const p=await razor('payments/'+encodeURIComponent(paymentId));if(p.order_id!==order.order_id||p.amount!==order.amount||p.currency!=='INR'||p.status!=='captured'||p.amount_refunded>0)throw new ApiError(409,'Payment is not yet captured, or it was refunded. Credits have not been added.');await run('UPDATE billing SET status=?,payment_id=? WHERE order_id=? AND status=?',['paid',p.id,order.order_id,'created']);}
export async function webhook(req:Request){const raw=await req.text();if(raw.length>100000)throw new ApiError(413,'Payload too large');const secret=setting('RAZORPAY_WEBHOOK_SECRET');if(!secret||!safeEqual(signed(raw,secret),req.headers.get('x-razorpay-signature')||''))throw new ApiError(401,'Invalid signature');const event=JSON.parse(raw);const p=event.payload?.payment?.entity;if(p?.order_id){const order=await one<Order>('SELECT * FROM billing WHERE order_id=?',[p.order_id]);if(order){if(event.event==='payment.captured'&&order.status==='created')await grant(order,p.id);if(event.event==='refund.processed'||event.event==='payment.refunded')await run('UPDATE billing SET status=? WHERE order_id=?',['refunded',order.order_id]);}}if(event.event==='refund.processed'){const paymentId=event.payload?.refund?.entity?.payment_id;if(paymentId)await run('UPDATE billing SET status=? WHERE payment_id=?',['refunded',paymentId]);}return Response.json({received:true});}
export async function commerce(req:Request,path:string[]){const a=(await user(req))!;
 if(path[0]==='my-tickets'){
  if(req.method!=='GET')throw new ApiError(405,'Method not allowed');
  const query=new URL(req.url).searchParams,page=Math.max(1,Math.min(10000,Number(query.get('page'))||1)),selling=query.get('kind')==='selling';
  const fields='t.id,t.movie,t.theater,t.show_at,t.language,t.format,t.quantity,t.price,t.status,t.created_at,(SELECT decision FROM admin_reviews WHERE ticket_id=t.id AND proof_id=t.proof_id ORDER BY created_at DESC,id DESC LIMIT 1) review_decision';
  const rows=selling?await all('SELECT '+fields+' FROM tickets t WHERE t.seller_id=? ORDER BY t.created_at DESC,t.id LIMIT 51 OFFSET ?',[a.id,(page-1)*50]):await all('SELECT '+fields+',r.amount,r.reserved_at,r.purchased_at,r.confirmed_at FROM tickets t LEFT JOIN ticket_receipts r ON r.listing_id=t.id AND r.buyer_id=t.buyer_id WHERE t.buyer_id=? ORDER BY COALESCE(r.reserved_at,t.created_at) DESC,t.id LIMIT 51 OFFSET ?',[a.id,(page-1)*50]);
  return Response.json({tickets:rows.slice(0,50),hasMore:rows.length>50,page,kind:selling?'selling':'purchases'});
 }
 if(path[0]==='billing'){
  const price=Number(setting('ALERT_PACK_PRICE_PAISE')||10000),credits=Number(setting('ALERT_PACK_CREDITS')||10);const ready=!!setting('RAZORPAY_KEY_ID')&&!!setting('RAZORPAY_KEY_SECRET')&&setting('BOOKING_FEED_READY')==='true'&&Number.isSafeInteger(price)&&price>=100&&Number.isSafeInteger(credits)&&credits>0;
  if(req.method==='GET')return Response.json({balance:await balance(a.id),ready,price:Number.isSafeInteger(price)&&price>=100?price:null,credits,verified:!!a.verified,orders:await all('SELECT order_id,amount,status,created_at FROM billing WHERE user_id=? ORDER BY created_at DESC LIMIT 20',[a.id])});
  if(req.method!=='POST')throw new ApiError(405,'Method not allowed');
  if(!ready)throw new ApiError(503,'Paid alerts open after live monitoring and payments are connected.');if(!a.verified)throw new ApiError(403,'Verify your email before buying credits.');await limit('billing:'+a.id,10);
  if(path[1]==='order'){const order=await razor('orders',{amount:price,currency:'INR',receipt:crypto.randomUUID(),notes:{product:'booking_alert_credits',user_id:a.id}});await run('INSERT INTO billing(order_id,user_id,amount,credits,created_at) VALUES(?,?,?,?,?)',[order.id,a.id,price,credits,now()]);return Response.json({orderId:order.id,amount:price,currency:'INR',key:setting('RAZORPAY_KEY_ID'),name:'Framefinder',description:credits+' booking alert credits'});}
  if(path[1]==='verify'){const p=z.object({razorpay_order_id:z.string().max(100),razorpay_payment_id:z.string().max(100),razorpay_signature:z.string().length(64)}).parse(await body(req));const order=await one<Order>('SELECT * FROM billing WHERE order_id=? AND user_id=?',[p.razorpay_order_id,a.id]);if(!order)throw new ApiError(404,'Order not found');if(!safeEqual(signed(order.order_id+'|'+p.razorpay_payment_id,setting('RAZORPAY_KEY_SECRET')),p.razorpay_signature))throw new ApiError(400,'Payment verification failed');await grant(order,p.razorpay_payment_id);return Response.json({ok:true,balance:await balance(a.id)});}
 }
 if(path[0]==='alerts'){
  if(!['GET','POST','PUT','DELETE'].includes(req.method))throw new ApiError(405,'Method not allowed');
  if(req.method!=='GET')await limit('alert-write:'+a.id,30,60);
  if(req.method==='GET'){const rows=await all<{payload:string}>('SELECT payload FROM user_alerts WHERE user_id=? ORDER BY created_at DESC',[a.id]);return Response.json({alerts:rows.map(r=>JSON.parse(r.payload)),monitoring:setting('BOOKING_FEED_READY')==='true',balance:await balance(a.id)});}
  if(req.method==='DELETE'){await run('DELETE FROM user_alerts WHERE id=? AND user_id=?',[path[1],a.id]);return Response.json({ok:true});}
  const p=alertSchema.parse(await body(req));if(p.date<indiaToday())throw new ApiError(400,'Choose a future show date.');const existing=await one<{user_id:string}>('SELECT user_id FROM user_alerts WHERE id=?',[p.id]);if(existing&&existing.user_id!==a.id)throw new ApiError(404,'Alert not found');const count=(await one<{n:number}>('SELECT COUNT(*) n FROM user_alerts WHERE user_id=?',[a.id]))?.n||0;if(!existing&&count>=50)throw new ApiError(400,'You can save up to 50 preferences.');await run('INSERT INTO user_alerts(id,user_id,payload,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload',[p.id,a.id,JSON.stringify(p),now()]);return Response.json({ok:true});
 }
 if(path[0]==='tickets'){
  if(req.method==='GET'){if(path[1]){const t=await one<any>('SELECT t.*,a.username,a.name FROM tickets t JOIN accounts a ON a.id=t.seller_id WHERE t.id=?',[path[1]]);if(!t||(t.seller_id!==a.id&&t.buyer_id!==a.id&&!['verified','reserved','completed'].includes(t.status)&&!(t.is_public&&t.status==='pending_verification')))throw new ApiError(404,'Listing not found');delete t.reference_hash;if(t.seller_id!==a.id)delete t.proof_id;return Response.json({review:await one('SELECT decision,created_at'+(t.seller_id===a.id?',note':'')+' FROM admin_reviews WHERE ticket_id=? AND proof_id=(SELECT proof_id FROM tickets WHERE id=?) ORDER BY created_at DESC,id DESC LIMIT 1',[t.id,t.id]),ticket:t,own:t.seller_id===a.id,agreedPrice:(await one<{amount:number}>("SELECT o.amount FROM ticket_offers o JOIN conversations c ON c.id=o.conversation_id WHERE c.ticket_id=? AND c.buyer_id=? AND o.status='accepted' ORDER BY o.updated_at DESC LIMIT 1",[t.id,a.id]))?.amount||null,checkoutReady:!!setting('TICKET_PARTNER_URL')});}return Response.json({tickets:await all(`SELECT t.id,t.movie,t.theater,t.show_at,t.language,t.format,t.quantity,t.price,t.face_value,t.is_public,t.status,(SELECT decision FROM admin_reviews WHERE ticket_id=t.id AND proof_id=t.proof_id ORDER BY created_at DESC,id DESC LIMIT 1) review_decision,a.username FROM tickets t JOIN accounts a ON a.id=t.seller_id WHERE ((t.status=? OR (t.is_public=1 AND t.status='pending_verification')) AND t.show_at>?) OR t.seller_id=? ORDER BY t.created_at DESC LIMIT 100`,['verified',now(),a.id]),partnerReady:!!setting('TICKET_PARTNER_URL')});}
  await limit('tickets:'+a.id,20);
  if(path[1]&&path[2]==='proof'){
   if(req.method!=='POST')throw new ApiError(405,'Method not allowed');const p=z.object({proofId:z.string().uuid()}).parse(await body(req));
   if(!await one('SELECT id FROM assets WHERE id=? AND user_id=? AND kind=?',[p.proofId,a.id,'proof']))throw new ApiError(400,'Upload your own booking proof first.');
   const changed=await run("UPDATE tickets SET proof_id=?,review_pending=1,status='pending_verification',is_public=0 WHERE id=? AND seller_id=? AND proof_id!=? AND show_at>? AND review_pending=0 AND status IN ('pending_verification','rejected') AND (SELECT decision FROM admin_reviews WHERE ticket_id=tickets.id AND proof_id=tickets.proof_id ORDER BY created_at DESC,id DESC LIMIT 1) IN ('needs_info','rejected')",[p.proofId,path[1],a.id,p.proofId,now()]);
   if(!changed.changes)throw new ApiError(409,'This ticket is not awaiting replacement proof, or it has already been resubmitted.');return Response.json({ok:true,status:'pending_verification'});
  }
  if(path[1]&&path[2]==='visibility'){const p=z.object({publish:z.boolean()}).parse(await body(req));const changed=await run('UPDATE tickets SET is_public=? WHERE id=? AND seller_id=? AND status IN (?,?)',[Number(p.publish),path[1],a.id,'pending_verification','verified']);if(!changed.changes)throw new ApiError(404,'Editable listing not found');return Response.json({ok:true});}

  if(path[1]&&path[2]==='cancel'){await run('UPDATE tickets SET status=? WHERE id=? AND seller_id=? AND status IN (?,?)',['cancelled',path[1],a.id,'pending_verification','verified']);return Response.json({ok:true});}
  if(path[1]&&path[2]==='checkout'){
   if(!a.verified)throw new ApiError(403,'Verify your email first.');const t=await one<any>('SELECT * FROM tickets WHERE id=? AND status=? AND show_at>?',[path[1],'verified',now()]);if(!t||t.seller_id===a.id)throw new ApiError(409,'This listing is unavailable.');const partner=setting('TICKET_PARTNER_URL');if(!partner||!setting('TICKET_PARTNER_TOKEN'))throw new ApiError(503,'Issuer transfer and marketplace payments are not connected.');const agreed=await one<{amount:number}>("SELECT o.amount FROM ticket_offers o JOIN conversations c ON c.id=o.conversation_id WHERE c.ticket_id=? AND c.buyer_id=? AND o.status='accepted' ORDER BY o.updated_at DESC LIMIT 1",[t.id,a.id]);const checkoutAmount=agreed?.amount||t.price;const reserved=await run('UPDATE tickets SET status=?,buyer_id=? WHERE id=? AND status=?',['reserved',a.id,t.id,'verified']);if(!reserved.changes)throw new ApiError(409,'Someone else reserved this ticket.');const stamp=now();await run('INSERT OR IGNORE INTO ticket_receipts(listing_id,buyer_id,amount,reserved_at,updated_at) VALUES(?,?,?,?,?)',[t.id,a.id,checkoutAmount,stamp,stamp]);
   try{const r=await fetch(partner.replace(/\/$/,'')+'/checkout',{method:'POST',headers:{Authorization:'Bearer '+setting('TICKET_PARTNER_TOKEN'),'Content-Type':'application/json','Idempotency-Key':t.id},body:JSON.stringify({listingId:t.id,buyerId:a.id,sellerId:t.seller_id,amount:checkoutAmount,currency:'INR',returnUrl:new URL('/tickets/'+t.id,req.url).href,showStartsAt:t.show_at,payoutCondition:'show_completed_without_open_dispute'}),signal:AbortSignal.timeout(15000)});const d=await r.json() as {url?:string};if(!r.ok||!d.url||new URL(d.url).protocol!=='https:')throw new Error();return Response.json({url:d.url});}catch{throw new ApiError(502,'Your reservation is pending reconciliation with the ticket partner. No second checkout will be opened.');}
  }
  const p=z.object({movie:z.string().trim().min(1).max(120),theater:z.string().trim().min(1).max(150),showAt:z.string().datetime({offset:true}),language:z.string().min(1).max(30),format:z.string().min(1).max(30),quantity:z.number().int().min(1).max(10),faceValue:z.number().int().positive().max(10000000),price:z.number().int().positive().max(10000000),proofId:z.string().uuid(),reference:z.string().min(6).max(100),publish:z.boolean().default(false)}).parse(await body(req));if(new Date(p.showAt)<=new Date())throw new ApiError(400,'The show must be in the future.');if(!await one('SELECT id FROM assets WHERE id=? AND user_id=? AND kind=?',[p.proofId,a.id,'proof']))throw new ApiError(400,'Upload your booking proof first.');const fingerprint=hash(p.reference.trim().toUpperCase());if(await one('SELECT id FROM tickets WHERE reference_hash=?',[fingerprint]))throw new ApiError(409,'This booking reference has already been submitted.');const id=crypto.randomUUID();await run('INSERT INTO tickets(id,seller_id,movie,theater,show_at,language,format,quantity,face_value,price,proof_id,reference_hash,created_at,is_public) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,a.id,p.movie,p.theater,new Date(p.showAt).toISOString(),p.language,p.format,p.quantity,p.faceValue,p.price,p.proofId,fingerprint,now(),Number(p.publish)]);const partner=setting('TICKET_PARTNER_URL');let verificationRequested=false;if(partner&&setting('TICKET_PARTNER_TOKEN')){try{const proof=await getAsset(p.proofId);if(!proof)throw new Error('Proof not found');const bytes=await new Response(proof.body).arrayBuffer();const r=await fetch(partner.replace(/\/$/,'')+'/verify',{method:'POST',headers:{Authorization:'Bearer '+setting('TICKET_PARTNER_TOKEN'),'Content-Type':'application/json','Idempotency-Key':id},body:JSON.stringify({listingId:id,sellerId:a.id,...p,proof:{mime:proof.mime,base64:Buffer.from(bytes).toString('base64')},callbackUrl:new URL('/api/v1/webhooks/tickets',req.url).href}),signal:AbortSignal.timeout(15000)});verificationRequested=r.ok;}catch{/* Keep verification pending for support reconciliation; never auto-approve proof. */}}return Response.json({id,status:'pending_verification',verificationRequested});
 }
 throw new ApiError(404,'Not found');
}
// A trusted issuer/marketplace service sends signed status events after validating the actual booking.
export async function ticketWebhook(req:Request){const raw=await req.text(),key=setting('TICKET_WEBHOOK_SECRET');if(!key||!safeEqual(signed(raw,key),req.headers.get('x-ticket-signature')||''))throw new ApiError(401,'Invalid signature');const p=z.object({listingId:z.string().uuid(),status:z.enum(['verified','rejected','completed','refunded','expired']),timestamp:z.number(),proofId:z.string().uuid().optional(),purchasedAt:z.string().datetime({offset:true}).optional()}).parse(JSON.parse(raw));if(Math.abs(Date.now()-p.timestamp)>300000)throw new ApiError(400,'Expired event');if(p.purchasedAt&&new Date(p.purchasedAt).getTime()>p.timestamp+300000)throw new ApiError(400,'Invalid purchase date');if(['verified','rejected'].includes(p.status)){const current=await one<any>('SELECT proof_id FROM tickets WHERE id=?',[p.listingId]);const replaced=await one('SELECT id FROM admin_reviews WHERE ticket_id=? AND proof_id!=? LIMIT 1',[p.listingId,current?.proof_id||'']);if(replaced&&p.proofId!==current?.proof_id)throw new ApiError(409,'Verification must reference the replacement proof.');}const from:Record<string,string[]>={verified:['pending_verification'],rejected:['pending_verification'],completed:['reserved'],refunded:['reserved','completed'],expired:['reserved','verified']};const states=from[p.status];const stamp=new Date(p.timestamp).toISOString();await batch([{sql:'UPDATE ticket_receipts SET updated_at=?,purchased_at=COALESCE(purchased_at,?),confirmed_at=COALESCE(confirmed_at,?) WHERE listing_id=? AND EXISTS(SELECT 1 FROM tickets WHERE id=? AND status IN ('+states.map(()=>'?').join(',')+'))',args:[stamp,p.status==='completed'?p.purchasedAt||null:null,p.status==='completed'?stamp:null,p.listingId,p.listingId,...states]},{sql:'UPDATE tickets SET status=? WHERE id=? AND status IN ('+states.map(()=>'?').join(',')+')',args:[p.status,p.listingId,...states]}]);return Response.json({ok:true});}
export async function bookingEvent(req:Request){if(setting('BOOKING_FEED_READY')!=='true')throw new ApiError(503,'Live monitoring is not enabled.');const raw=await req.text(),key=setting('BOOKING_WEBHOOK_SECRET');if(!key||!safeEqual(signed(raw,key),req.headers.get('x-booking-signature')||''))throw new ApiError(401,'Invalid signature');const p=z.object({eventId:z.string().min(1).max(150),alertId:z.string().min(1).max(80),title:z.string().max(120),city:z.string(),language:z.string(),edition:z.string(),theaterId:z.string(),format:z.string(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),bookingUrl:z.string().url(),observedAt:z.string().datetime(),bookable:z.literal(true)}).parse(JSON.parse(raw));if(Math.abs(Date.now()-new Date(p.observedAt).getTime())>300000)throw new ApiError(400,'Stale booking observation');const row=await one<{user_id:string;payload:string}>('SELECT user_id,payload FROM user_alerts WHERE id=?',[p.alertId]);if(!row||await one('SELECT user_id FROM removed_accounts WHERE user_id=?',[row.user_id]))throw new ApiError(404,'Alert not found');const pref=alertSchema.parse(JSON.parse(row.payload));const link=new URL(p.bookingUrl);if(link.protocol!=='https:'||link.hostname!=='in.bookmyshow.com')throw new ApiError(400,'Invalid booking link');if(pref.title.toLowerCase()!==p.title.toLowerCase()||pref.city!==p.city||pref.language!==p.language||pref.edition!==p.edition||pref.date!==p.date||!pref.theaterIds.includes(p.theaterId)||!pref.formats.includes(p.format as any)||p.time<pref.timeFrom||p.time>pref.timeTo)throw new ApiError(400,'Show does not match the alert');
 if(new Date(p.date+'T'+p.time+':00+05:30').getTime()<Date.now())throw new ApiError(400,'Show time has passed');if(pref.bookingUrl&&extractEventCode(pref.bookingUrl)!==extractEventCode(p.bookingUrl))throw new ApiError(400,'Movie release does not match');const id=hash(row.user_id+':'+p.eventId);const stamp=now();const debit=await run("INSERT OR IGNORE INTO credit_uses(event_id,user_id,created_at) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM credit_uses WHERE user_id=?) < 3+(SELECT COALESCE(SUM(credits),0) FROM billing WHERE user_id=? AND status='paid')",[id,row.user_id,stamp,row.user_id,row.user_id]);
 // Idempotent retry repairs an interrupted insert after the debit; the credit and notification share an ID.
 const charged=await one('SELECT event_id FROM credit_uses WHERE event_id=?',[id]);if(charged)await notify(id,row.user_id,p.title+' booking is open',p.date+' · '+p.time+' IST · '+p.format+' · '+(theaters.find(t=>t.id===p.theaterId)?.name||p.theaterId),p.bookingUrl);return Response.json({delivered:!!charged,duplicate:!debit.changes&&!!charged,credits:await balance(row.user_id)});
}
