import {z} from 'zod';
import {all,one,run,batch,setting} from '@/lib/platform';
import {ApiError,user,body,now,hash,signed,safeEqual,limit} from './security';
import {seatAlertSchema} from '@/lib/seat-alerts';
import {indiaToday,extractEventCode,theaters} from '@/lib/booking';
export async function seatAlerts(req:Request,path:string[]){const a=(await user(req))!;if(req.method==='GET'){const rows=await all<{payload:string}>('SELECT payload FROM seat_alerts WHERE user_id=? ORDER BY created_at DESC',[a.id]);return Response.json({alerts:rows.map(r=>JSON.parse(r.payload)),monitoring:setting('SEAT_FEED_READY')==='true'});}if(req.method==='DELETE'){await run('DELETE FROM seat_alerts WHERE id=? AND user_id=?',[path[1],a.id]);return Response.json({ok:true});}if(req.method!=='POST'&&req.method!=='PUT')throw new ApiError(405,'Method not allowed');await limit('seat-alert:'+a.id,30);const p=seatAlertSchema.parse(await body(req));if(p.dates.some(d=>d<indiaToday()))throw new ApiError(400,'Choose today or future dates.');const row=await one<{user_id:string}>('SELECT user_id FROM seat_alerts WHERE id=?',[p.id]);if(row&&row.user_id!==a.id)throw new ApiError(404,'Alert not found');if(!row&&(await one<{n:number}>('SELECT COUNT(*) n FROM seat_alerts WHERE user_id=?',[a.id]))!.n>=50)throw new ApiError(400,'You can save up to 50 alerts.');p.dates.sort();await run('INSERT INTO seat_alerts(id,user_id,payload,created_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload',[p.id,a.id,JSON.stringify(p),now()]);return Response.json({ok:true});}
const observation=z.object({alertId:z.string().uuid(),provider:z.string().min(1).max(60),sessionId:z.string().min(1).max(100),layoutId:z.string().min(1).max(100),city:z.literal('Hyderabad'),theaterId:z.string(),title:z.string(),date:z.string(),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),bookingUrl:z.string().url(),observedAt:z.string().datetime(),complete:z.literal(true),seats:z.record(z.enum(['available','held','sold','unavailable']))});
export async function seatSnapshot(req:Request){if(setting('SEAT_FEED_READY')!=='true')throw new ApiError(503,'Seat monitoring is not connected.');const raw=await req.text();if(raw.length>200000)throw new ApiError(413,'Snapshot too large');const key=setting('SEAT_WEBHOOK_SECRET');if(!key||!safeEqual(signed(raw,key),req.headers.get('x-seat-signature')||''))throw new ApiError(401,'Invalid signature');const p=observation.parse(JSON.parse(raw));if(!Object.keys(p.seats).length||Object.keys(p.seats).length>5000)throw new ApiError(400,'A complete, non-empty seat map is required.');if(Object.keys(p.seats).some(id=>id.length>80))throw new ApiError(400,'Invalid seat ID');const ts=new Date(p.observedAt);if(Date.now()-ts.getTime()>300000||ts.getTime()>Date.now()+30000)throw new ApiError(400,'Stale observation');const row=await one<{payload:string;user_id:string}>('SELECT payload,user_id FROM seat_alerts WHERE id=?',[p.alertId]);if(!row)throw new ApiError(404,'Alert not found');const pref=seatAlertSchema.parse(JSON.parse(row.payload));if(pref.city!==p.city||pref.theaterId!==p.theaterId||pref.title.toLowerCase()!==p.title.toLowerCase()||!pref.dates.includes(p.date))throw new ApiError(400,'Snapshot does not match your alert');if(!extractEventCode(p.bookingUrl)||(pref.bookingUrl&&extractEventCode(pref.bookingUrl)!==extractEventCode(p.bookingUrl)))throw new ApiError(400,'Invalid movie booking link');if(new Date(p.date+'T'+p.time+':00+05:30').getTime()<=Date.now())throw new ApiError(400,'Show time has passed');
const observationKey=hash(JSON.stringify([pref,p.provider,p.sessionId,p.date,p.layoutId]));const stamp=ts.toISOString();const old=await one<{payload:string;observed_at:string}>('SELECT * FROM seat_observations WHERE key=?',[observationKey]);const eventId=hash(observationKey+':'+stamp);let released:string[]=[];
if(!old){await run('INSERT OR IGNORE INTO seat_observations(key,payload,observed_at) VALUES(?,?,?)',[observationKey,JSON.stringify(p.seats),stamp]);return Response.json({baseline:true,released:[],delivered:false});}
if(stamp>old.observed_at){const before=JSON.parse(old.payload);released=Object.keys(p.seats).filter(id=>before[id]&&before[id]!=='available'&&p.seats[id]==='available');const event={title:p.title,message:`${released.length} seats became available · ${p.date} ${p.time} IST · ${theaters.find(t=>t.id===p.theaterId)?.name||p.theaterId}`,link:p.bookingUrl,released,observedAt:stamp};const statements=[];if(released.length)statements.push({sql:'INSERT OR IGNORE INTO seat_events(id,user_id,payload) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM seat_observations WHERE key=? AND observed_at=?)',args:[eventId,row.user_id,JSON.stringify(event),observationKey,old.observed_at]});statements.push({sql:'UPDATE seat_observations SET payload=?,observed_at=? WHERE key=? AND observed_at=?',args:[JSON.stringify(p.seats),stamp,observationKey,old.observed_at]});await batch(statements);}
const queued=await one<{payload:string;delivered:number}>('SELECT payload,delivered FROM seat_events WHERE id=?',[eventId]);if(!queued)return Response.json({baseline:false,released:[],delivered:false});const e=JSON.parse(queued.payload);if(!queued.delivered){await run("INSERT OR IGNORE INTO credit_uses(event_id,user_id,created_at) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM credit_uses WHERE user_id=?) < 3+(SELECT COALESCE(SUM(credits),0) FROM billing WHERE user_id=? AND status='paid')",[eventId,row.user_id,now(),row.user_id,row.user_id]);if(await one('SELECT event_id FROM credit_uses WHERE event_id=?',[eventId]))await batch([{sql:'INSERT OR IGNORE INTO notifications(id,user_id,title,message,link,created_at) VALUES(?,?,?,?,?,?)',args:[eventId,row.user_id,e.title+' · seats released',e.message,e.link,now()]},{sql:'UPDATE seat_events SET delivered=1 WHERE id=?',args:[eventId]}]);}
return Response.json({released:e.released,delivered:!!(await one<{delivered:number}>('SELECT delivered FROM seat_events WHERE id=?',[eventId]))?.delivered});}
