import {visiblePicture} from '@/lib/profile-pictures';
import {scrypt,randomBytes,createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {one,run,setting} from '@/lib/platform';
export class ApiError extends Error{constructor(public status:number,message:string,public retryAfter?:number){super(message);}}
export const now=()=>new Date().toISOString();
export const token=()=>randomBytes(32).toString('hex');
export const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
function derivePassword(password:string,salt:string){return new Promise<Buffer>((resolve,reject)=>scrypt(password,salt,64,{N:32768,r:8,p:3,maxmem:64*1024*1024},(error,key)=>error?reject(error):resolve(key)));}
export async function passwordHash(password:string){const salt=randomBytes(16).toString('hex');return salt+':'+(await derivePassword(password,salt)).toString('hex');}
export async function passwordMatches(password:string,encoded:string){const[salt,value]=encoded.split(':');if(!salt||!value)return false;const result=await derivePassword(password,salt),target=Buffer.from(value,'hex');return result.length===target.length&&timingSafeEqual(result,target);}
export function signed(value:string,secret:string){return createHmac('sha256',secret).update(value).digest('hex');}
export function safeEqual(a:string,b:string){const x=Buffer.from(a);const y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
export function cookie(req:Request,name:string){const raw=(req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='));return raw?decodeURIComponent(raw.slice(name.length+1)):'';}
export function sessionCookie(value:string,age=60*60*24*14){return `ff_session=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;}
export type Account={id:string;email:string;username:string;name:string;bio:string;avatar:string;languages:string;onboarded:number;verified:number;password:string|null;google_id:string|null;created_at:string};
export function publicAccount(a:Account){return {id:a.id,username:a.username,name:a.name,bio:a.bio,avatar:visiblePicture(a.avatar),languages:JSON.parse(a.languages),onboarded:!!a.onboarded,joined:a.created_at};}
export async function user(req:Request,required=true){const t=cookie(req,'ff_session');const a=t?await one<Account>('SELECT a.* FROM accounts a JOIN sessions s ON s.user_id=a.id WHERE s.token=? AND s.expires>? AND NOT EXISTS(SELECT 1 FROM removed_accounts WHERE user_id=a.id)',[hash(t),now()]):null;if(!a&&required)throw new ApiError(401,'Please sign in to continue.');return a;}
export async function newSession(id:string){if(await one('SELECT user_id FROM removed_accounts WHERE user_id=?',[id]))throw new ApiError(403,'This account has been removed. Contact the team for help.');const t=token();await run('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',[hash(t),id,new Date(Date.now()+14*86400000).toISOString()]);return sessionCookie(t);}
let lastLimitCleanup=0;
export async function limit(key:string,max=15,seconds=900){const bucket=Math.floor(Date.now()/1000/seconds);const k=hash(key)+':'+bucket;const r=await one<{count:number}>('INSERT INTO limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',[k,(bucket+1)*seconds]);if((r?.count||0)>max)throw new ApiError(429,'Too many attempts. Please try again later.',Math.max(1,(bucket+1)*seconds-Math.floor(Date.now()/1000)));if(Date.now()-lastLimitCleanup>3600000){lastLimitCleanup=Date.now();await run('DELETE FROM limits WHERE key IN (SELECT key FROM limits WHERE expires<? ORDER BY expires LIMIT 1000)',[Math.floor(Date.now()/1000)]);}}
export function originCheck(req:Request){if(['GET','HEAD'].includes(req.method))return;const origin=req.headers.get('origin');if(!origin||new URL(origin).origin!==new URL(req.url).origin)throw new ApiError(403,'Please submit this form from the website.');}
export async function body(req:Request,max=60000){if(Number(req.headers.get('content-length')||0)>max)throw new ApiError(413,'Request is too large.');const text=await req.text();if(text.length>max)throw new ApiError(413,'Request is too large.');try{return JSON.parse(text);}catch{throw new ApiError(400,'Invalid request.');}}
export async function captcha(req:Request,value:string){const secret=setting('TURNSTILE_SECRET_KEY');if(!secret){if(setting('REQUIRE_CAPTCHA')==='true')throw new ApiError(503,'Security verification is not configured yet.');return;}if(!value)throw new ApiError(400,'Complete the security verification.');const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:new URLSearchParams({secret,response:value}),signal:AbortSignal.timeout(8000)});const d=await r.json() as {success?:boolean;hostname?:string};if(!d.success||d.hostname!==new URL(req.url).hostname)throw new ApiError(400,'Security verification expired. Please retry.');}
export async function sendMail(email:string,subject:string,text:string){const key=setting('RESEND_API_KEY'),from=setting('MAIL_FROM');if(!key||!from)throw new ApiError(503,'Email delivery has not been configured.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject,text}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new ApiError(503,'Could not send email. Please retry later.');}
