import {notify} from './notifications';
import {z} from 'zod';
import {all,one,run,batch,putAsset,getAsset,setting} from '@/lib/platform';
import {ApiError,user,publicAccount,body,now,limit,hash,type Account} from './security';
import {catalog,findFilm,movies,providers,hasPoster,type Film} from './catalog';
const stateSchema=z.object({rating:z.number().int().min(1).max(10).nullable().optional(),liked:z.boolean().optional(),watched:z.boolean().optional(),watchlist:z.boolean().optional(),watchedOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().optional(),review:z.string().max(3000).optional(),spoiler:z.boolean().optional()}).strict();
export async function social(req:Request,path:string[]){
 const url=new URL(req.url);const a=(await user(req))!;
 if(path[0]==='movies'&&path.length===1)return Response.json(await movies(url));
 if(path[0]==='movies'&&path[1]){const id=Number(path[1]);if(!Number.isSafeInteger(id)||id<1)throw new ApiError(400,'Invalid film');const film=await findFilm(id);if(!film)throw new ApiError(404,'Film not found');
  if(path[2]==='providers')return Response.json(await providers(film,/^[A-Z]{2}$/.test(url.searchParams.get('region')||'')?url.searchParams.get('region')!:'IN'));
  if(req.method==='GET'){const stats=await one('SELECT COUNT(CASE WHEN watched=1 THEN 1 END) AS watched, COUNT(CASE WHEN liked=1 THEN 1 END) AS likes, AVG(rating)/2.0 AS rating, COUNT(rating) AS ratings FROM social_state WHERE movie_id=?',[id]);const reviews=await all('SELECT s.review,s.rating,s.spoiler,s.updated_at,a.username,a.name,a.avatar FROM social_state s JOIN accounts a ON a.id=s.user_id WHERE s.movie_id=? AND s.review != ? ORDER BY s.updated_at DESC LIMIT 50',[id,'']);return Response.json({movie:film,state:await one('SELECT * FROM social_state WHERE user_id=? AND movie_id=?',[a.id,id]),stats,reviews});}
  const data=stateSchema.parse(await body(req));const key=a.id+':'+id;await run('INSERT OR IGNORE INTO social_state(key,user_id,movie_id,updated_at) VALUES(?,?,?,?)',[key,a.id,id,now()]);const columns:Record<string,string>={rating:'rating',liked:'liked',watched:'watched',watchlist:'watchlist',watchedOn:'watched_on',review:'review',spoiler:'spoiler'};const entries=Object.entries(data);if(entries.length)await run('UPDATE social_state SET '+entries.map(([k])=>columns[k]+'=?').join(',')+',updated_at=? WHERE key=?',[...entries.map(([,v])=>typeof v==='boolean'?Number(v):v),now(),key]);return Response.json({ok:true});
 }
 if(path[0]==='state'){const state=await all<any>('SELECT * FROM social_state WHERE user_id=? ORDER BY updated_at DESC',[a.id]);const ids=state.map(s=>s.movie_id);const films=await Promise.all(ids.slice(0,100).map(findFilm));return Response.json({state,movies:films.filter(Boolean),total:state.length});}
 if(path[0]==='recommendations'){
  const history=await all<any>('SELECT movie_id,rating,liked,watched FROM social_state WHERE user_id=?',[a.id]);if(setting('JAVA_RECOMMENDER_URL')){const upstream=new URL(setting('JAVA_RECOMMENDER_URL'));if(upstream.protocol!=='https:')throw new ApiError(503,'Recommendation service requires HTTPS.');const response=await fetch(upstream,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+setting('JAVA_RECOMMENDER_TOKEN')},body:JSON.stringify({ratings:Object.fromEntries(history.filter(s=>s.rating||s.liked).map(s=>[String(s.movie_id),s.rating?s.rating/2:4])),mood:url.searchParams.get('mood')||'All moods',language:url.searchParams.get('language')||JSON.parse(a.languages)[0]||'Any language',maxMinutes:600}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new ApiError(503,'Your recommendation service is unavailable.');return Response.json(await response.json());}const liked=await Promise.all(history.filter(s=>s.liked||s.rating>=7).slice(0,40).map(s=>findFilm(s.movie_id)));const favorites=liked.filter(Boolean) as Film[];const requestedLanguage=url.searchParams.get('language')||'';const langs=requestedLanguage?[requestedLanguage]:JSON.parse(a.languages) as string[];const mood=url.searchParams.get('mood')||'';const watched=new Set(history.filter(s=>s.watched||s.rating).map(s=>s.movie_id));
  let candidates=catalog;if(setting('TMDB_READ_TOKEN')){const selected=langs.length?langs.slice(0,4):[''];const pages=await Promise.allSettled(selected.flatMap(language=>[1,2].map(page=>movies(new URL('https://local/?language='+encodeURIComponent(language)+'&page='+page)))));const remote=pages.flatMap(p=>p.status==='fulfilled'?p.value.movies:[]);const merged=new Map(catalog.map(m=>[(m.title.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'')+':'+m.year),m]));for(const m of remote){const k=m.title.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'')+':'+m.year;if(!merged.has(k))merged.set(k,m);}candidates=[...merged.values()];}
  const score=(m:Film)=>favorites.reduce((n,f)=>n+m.genres.filter(g=>f.genres.includes(g)).length/Math.sqrt(Math.max(1,m.genres.length*f.genres.length)),0)+(langs.includes(m.language)?1:0)+(mood&&m.moods.includes(mood)?2:0);
  const ranked=candidates.filter(m=>hasPoster(m)&&!watched.has(m.id)&&(!langs.length||langs.includes(m.language))).map(m=>({...m,score:score(m),reason:favorites.length?`Shares ${m.genres.filter(g=>favorites.some(f=>f.genres.includes(g))).slice(0,2).join(' / ')||'your selected language'} with films you like`:'Explore a film in your selected languages'})).sort((x,y)=>y.score-x.score||x.id-y.id);
  const balanced=langs.length>1?Array.from({length:48},(_,i)=>langs.map(lang=>ranked.filter(m=>m.language===lang)[i])).flat().filter(Boolean).slice(0,48):ranked.slice(0,48);
  return Response.json({movies:balanced,method:'Genre similarity + language preferences',rated:history.length});
 }
 if(path[0]==='me'){
  if(req.method==='GET')return Response.json({user:publicAccount(a)});
  const p=z.object({name:z.string().trim().min(1).max(60),bio:z.string().max(300),languages:z.array(z.enum(['English','Telugu','Hindi','Tamil','Malayalam','Kannada','Korean','Japanese','French'])).min(1).max(9),onboarded:z.boolean().optional()}).parse(await body(req));await run('UPDATE accounts SET name=?,bio=?,languages=?,onboarded=? WHERE id=?',[p.name,p.bio,JSON.stringify(p.languages),p.onboarded?1:a.onboarded,a.id]);return Response.json({ok:true});
 }
 if(path[0]==='members'){
  if(!path[1]){const q=(url.searchParams.get('q')||'').trim().toLowerCase().replaceAll('%','').replaceAll('_','').slice(0,60);const members=await all<Account>('SELECT * FROM accounts WHERE lower(username) LIKE ? OR lower(name) LIKE ? ORDER BY created_at DESC LIMIT 40',['%'+q+'%','%'+q+'%']);return Response.json({members:members.map(publicAccount)});}
  const member=await one<Account>('SELECT * FROM accounts WHERE username=? COLLATE NOCASE',[path[1].trim()]);if(!member)throw new ApiError(404,'Member not found');
  if(path[2]==='follow'){if(member.id===a.id)throw new ApiError(400,'This is your profile.');const p=z.object({following:z.boolean()}).parse(await body(req));if(p.following){const inserted=await run('INSERT OR IGNORE INTO follows(key,follower,following) VALUES(?,?,?)',[a.id+':'+member.id,a.id,member.id]);if(inserted.changes)await notify('follow:'+a.id+':'+member.id,member.id,'New follower',`@${a.username} is now following you.`,'/members/'+a.username);}else await run('DELETE FROM follows WHERE follower=? AND following=?',[a.id,member.id]);return Response.json({ok:true});}
  if(path[2]==='followers'||path[2]==='following'){if(req.method!=='GET')throw new ApiError(405,'Method not allowed');const page=Math.max(1,Math.min(10000,Number(url.searchParams.get('page'))||1));const followers=path[2]==='followers';const rows=await all<Account>('SELECT a.* FROM accounts a JOIN follows f ON a.id=f.'+(followers?'follower':'following')+' WHERE f.'+(followers?'following':'follower')+'=? ORDER BY a.username LIMIT 50 OFFSET ?',[member.id,(page-1)*50]);return Response.json({members:rows.map(publicAccount),page,hasMore:rows.length===50});}
  const state=await all<any>('SELECT movie_id,rating,liked,watched,watched_on,review,spoiler,updated_at FROM social_state WHERE user_id=? AND (watched=1 OR liked=1 OR review != ?) ORDER BY updated_at DESC LIMIT 100',[member.id,'']);const films=await Promise.all(state.map(s=>findFilm(s.movie_id)));return Response.json({member:publicAccount(member),state,movies:films.filter(Boolean),followingCount:(await one<{n:number}>('SELECT COUNT(*) n FROM follows WHERE follower=?',[member.id]))?.n||0,followsYou:!!await one('SELECT key FROM follows WHERE follower=? AND following=?',[member.id,a.id]),followerPreview:(await all<Account>('SELECT a.* FROM accounts a JOIN follows f ON f.follower=a.id WHERE f.following=? ORDER BY a.username LIMIT 8',[member.id])).map(publicAccount),followedBy:(await all<Account>('SELECT a.* FROM accounts a JOIN follows f ON a.id=f.follower JOIN follows mine ON mine.following=f.follower WHERE f.following=? AND mine.follower=? LIMIT 12',[member.id,a.id])).map(publicAccount),followers:(await one<{n:number}>('SELECT COUNT(*) n FROM follows WHERE following=?',[member.id]))?.n||0,following:!!await one('SELECT key FROM follows WHERE follower=? AND following=?',[a.id,member.id])});
 }
 if(path[0]==='assets'){
  if(req.method==='GET'){const asset=await one<any>('SELECT * FROM assets WHERE id=?',[path[1]]);if(!asset||(asset.kind!=='avatar'&&asset.user_id!==a.id))throw new ApiError(404,'Image not found');const file=await getAsset(asset.id);if(!file)throw new ApiError(404,'Image not found');return new Response(file.body,{headers:{'Content-Type':file.mime,'Cache-Control':asset.kind==='avatar'?'private,max-age=3600':'no-store','X-Content-Type-Options':'nosniff'}});}
  await limit('upload:'+a.id,15);if(Number(req.headers.get('content-length')||0)>4_300_000)throw new ApiError(413,'Choose an image smaller than 4 MB.');const form=await req.formData();const file=form.get('file');const kind=form.get('kind');if(!(file instanceof File)||!['avatar','proof'].includes(String(kind))||file.size>4*1024*1024)throw new ApiError(400,'Upload a JPG, PNG or WebP image under 4 MB.');const bytes=await file.arrayBuffer(),b=new Uint8Array(bytes);const valid=(file.type==='image/jpeg'&&b[0]===255&&b[1]===216&&b[2]===255)||(file.type==='image/png'&&[137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))||(file.type==='image/webp'&&String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP');if(!valid)throw new ApiError(400,'Unsupported image.');const id=crypto.randomUUID();await putAsset(id,bytes,file.type);await run('INSERT INTO assets(id,user_id,kind,mime) VALUES(?,?,?,?)',[id,a.id,kind,file.type]);if(kind==='avatar')await run('UPDATE accounts SET avatar=? WHERE id=?',['/api/v1/assets/'+id,a.id]);return Response.json({id,url:'/api/v1/assets/'+id});
 }
 if(path[0]==='import'){
  const p=z.object({rows:z.array(z.object({title:z.string().max(200),year:z.number().int(),rating:z.number().min(0.5).max(5).nullable()})).max(2000)}).parse(await body(req,500000));let matched=0;const statements=[];const unmatched:string[]=[];for(const row of p.rows){const film=catalog.find(m=>m.title.toLowerCase()===row.title.toLowerCase()&&m.year===row.year);if(!film){unmatched.push(row.title);continue;}matched++;statements.push({sql:'INSERT INTO social_state(key,user_id,movie_id,rating,watched,updated_at) VALUES(?,?,?,?,1,?) ON CONFLICT(key) DO UPDATE SET rating=excluded.rating,watched=1,updated_at=excluded.updated_at',args:[a.id+':'+film.id,a.id,film.id,row.rating===null?null:Math.round(row.rating*2),now()]});}for(let i=0;i<statements.length;i+=40)await batch(statements.slice(i,i+40));return Response.json({matched,unmatched:unmatched.slice(0,30),unmatchedCount:unmatched.length});
 }
 if(path[0]==='notifications'){return Response.json({notifications:await all('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50',[a.id])});}
 throw new ApiError(404,'Not found');
}
