// Server-only Turso SQL-over-HTTP + private Supabase Storage adapter for Vercel.
export const setting=(name:string)=>process.env[name]||'';
type Statement={sql:string;args?:unknown[]};
function arg(value:unknown){if(value===null||value===undefined)return {type:'null'};if(typeof value==='number')return {type:Number.isInteger(value)?'integer':'float',value:String(value)};return {type:'text',value:String(value)};}
function operation(s:Statement){return {type:'execute',stmt:{sql:s.sql,args:(s.args||[]).map(arg)}};}
async function pipeline(requests:unknown[],baton?:string,streamUrl?:string){const base=setting('TURSO_HTTP_URL').replace(/^(libsql|turso):/,'https:').replace(/\/$/,'');if(!base||!setting('TURSO_AUTH_TOKEN'))throw new Error('Configure TURSO_HTTP_URL and TURSO_AUTH_TOKEN');const target=new URL('v2/pipeline',(streamUrl||base).replace(/\/?(?:v2\/pipeline)?$/,'/'));if(target.protocol!=='https:'||target.username||target.password)throw new Error('Invalid database stream URL');const r=await fetch(target,{method:'POST',headers:{Authorization:'Bearer '+setting('TURSO_AUTH_TOKEN'),'Content-Type':'application/json'},body:JSON.stringify({requests,baton:baton||null}),cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Database request failed');return r.json() as Promise<any>;}
function result(r:any){if(r.type!=='ok')throw new Error('Database operation failed');return r.response.result;}
function rows<T>(r:any):T[]{return (r.rows||[]).map((row:any[])=>Object.fromEntries(row.map((cell:any,i:number)=>[r.cols[i].name,cell.type==='null'?null:['integer','float'].includes(cell.type)?Number(cell.value):cell.value])));}
export async function all<T=Record<string,unknown>>(sql:string,args:unknown[]=[]){const r=await pipeline([operation({sql,args}),{type:'close'}]);return rows<T>(result(r.results[0]));}
export async function one<T=Record<string,unknown>>(sql:string,args:unknown[]=[]){return (await all<T>(sql,args))[0]||null;}
export async function run(sql:string,args:unknown[]=[]){const r=await pipeline([operation({sql,args}),{type:'close'}]);return {changes:Number(result(r.results[0]).affected_row_count)};}
export async function batch(statements:Statement[]){if(!statements.length)return [];const start=await pipeline([operation({sql:'BEGIN IMMEDIATE'})]);result(start.results[0]);let baton=start.baton as string|undefined,streamUrl=start.base_url as string|undefined;try{const res=await pipeline(statements.map(operation),baton,streamUrl);baton=res.baton;streamUrl=res.base_url||streamUrl;const results=res.results.map(result);const commit=await pipeline([operation({sql:'COMMIT'}),{type:'close'}],baton,streamUrl);result(commit.results[0]);return results;}catch(e){if(baton)await pipeline([operation({sql:'ROLLBACK'}),{type:'close'}],baton,streamUrl).catch(()=>{});throw e;}}
function assetUrl(key:string){const base=setting('SUPABASE_URL'),bucket=setting('SUPABASE_STORAGE_BUCKET');if(!base||!bucket||!setting('SUPABASE_SERVICE_ROLE_KEY'))throw new Error('Configure private image storage');return base.replace(/\/$/,'')+'/storage/v1/object/'+encodeURIComponent(bucket)+'/'+encodeURIComponent(key);}
function storageHeaders(){const key=setting('SUPABASE_SERVICE_ROLE_KEY');return {Authorization:'Bearer '+key,apikey:key};}
export async function putAsset(key:string,bytes:ArrayBuffer,mime:string){const r=await fetch(assetUrl(key),{method:'POST',headers:{...storageHeaders(),'Content-Type':mime,'x-upsert':'false'},body:bytes});if(!r.ok)throw new Error('Image upload failed');}
export async function getAsset(key:string){const r=await fetch(assetUrl(key),{headers:storageHeaders(),cache:'no-store'});if(r.status===404)return null;if(!r.ok)throw new Error('Image unavailable');return {body:r.body,mime:r.headers.get('Content-Type')||'application/octet-stream'};}

export async function deleteAsset(key:string){const r=await fetch(assetUrl('').replace(/\/$/,''),{method:"DELETE",headers:{...storageHeaders(),'Content-Type':'application/json'},body:JSON.stringify({prefixes:[key]}),signal:AbortSignal.timeout(8000)});if(!r.ok&&r.status!==404)throw new Error("Image erasure deferred");}
